import 'package:flutter/material.dart';

import 'localized_text.dart';

class AppLocalizations {
  AppLocalizations(this.languageCode);

  final String languageCode;

  static const supportedLocales = [
    Locale('en'),
    Locale('it'),
    Locale('fr'),
    Locale('es'),
    Locale('fa'),
    Locale('ar'),
  ];

  static const rtlLanguages = {'fa', 'ar'};

  bool get isRtl => rtlLanguages.contains(languageCode);

  static Map<String, Map<String, String>> get localizedValues =>
      _localizedValues;

  String t(String key) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        _localizedValues['it']?[key] ??
        key;
  }

  String localizedMap(Map<String, dynamic> values, {String fallback = ''}) {
    return resolveLocalizedText(
      values,
      languageCode,
      fallback: fallback,
    );
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'UfficioFacile',
      'hero_title':
          'Tell us the problem. We’ll find the right Italian procedure.',
      'hero_subtitle':
          'Use normal words: bills, ASL, rent contract, university, INPS, documents. UfficioFacile matches your issue with the right category, steps, documents, and contacts.',
      'start_problem': 'Start from my problem',
      'browse_procedures': 'Browse procedures',
      'utilities_bills': 'Bills and utilities',
      'saved_requests': 'Saved requests',
      'what_help': 'What do you need help with?',
      'onboarding_title': 'Italian admin, step by step.',
      'onboarding_subtitle':
          'Organize procedures, reminders, documents, and formal messages for bills, rent, health, university, and public offices.',
      'privacy_title': 'Privacy and disclaimer',
      'skip': 'Skip',
      'next': 'Next',
      'done': 'Done',
      'profile': 'Profile',
      'help': 'Help',
      'admin': 'Admin',
      'generate_pack': 'Generate pack',
      'save_request': 'Save request',
      'copied': 'Copied',
      'request_saved': 'Request saved',
      'short_message': 'Short message',
      'email': 'Email',
      'pec': 'PEC / Formal',
      'follow_up': 'Follow-up',
      'strong_follow_up': 'Stronger follow-up',
      'attachments': 'Attachments',
      'next_steps': 'Next steps',
      'warnings': 'Warnings',
      'disclaimer_short':
          'Practical drafting and organization support only. Always verify the final instructions on the official website or with the competent office.',
      'upcoming_reminders': 'Upcoming reminders',
      'requests_follow_up': 'Needs follow-up',
      'drafts': 'Drafts',
      'recent_requests': 'Recent requests',
      'problem_examples': 'Examples',
      'recommendations': 'Recommended workflows',
      'no_results':
          'No close match yet. You can still use the general formal request.',
      'compare_offers': 'Compare offers',
      'understand_bill': 'Understand my bill',
      'canone_rai': 'Canone RAI',
      'telecom': 'Internet and phone',
      'admin_panel': 'Admin panel',
      'demo_data': 'Demo data',
      'scan_situation': 'Scan my situation',
      'city_packs': 'City packs',
      'student_mode': 'Student mode',
      'tenant_mode': 'Tenant mode',
      'life_checklist': 'My Italy checklist',
      'proof_folder': 'Proof folder',
      'official_links': 'Official links',
      'cost_dashboard': 'Cost dashboard',
      'document_vault': 'Document vault',
      'contacts_directory': 'Contacts directory',
      'calendar': 'Calendar',
      'plan': 'Plan',
      'free_plan': 'Free',
      'pro_plan': 'Premium',
      'consultant_plan': 'Consultant',
      'beta_access_active': 'Beta access active',
      'upgrade_to_pro': 'Upgrade to Premium',
      'premium_feature': 'Premium feature',
      'auth_account': 'Account',
      'auth_login': 'Log in',
      'auth_create_account': 'Create account',
      'auth_email': 'Email',
      'auth_password': 'Password',
      'auth_continue_public': 'Continue browsing public guides',
      'auth_login_subtitle':
          'Use your email and password to open your private workspace.',
      'auth_signup_subtitle':
          'Create an account to save and sync your requests, reminders, and document details.',
      'auth_login_or_signup': 'Log in or create account',
      'auth_required_title': 'Account required',
      'auth_required_message':
          'Create an account to save and sync your documents, requests, and reminders.',
      'auth_required_feature': 'You need an account to open this area.',
      'auth_wait': 'Please wait...',
      'auth_reset_password': 'Send password reset email',
      'auth_reset_sent': 'Password reset email sent. Check your inbox.',
      'auth_signup_success':
          'Account created. If email confirmation is enabled, confirm your email before signing in.',
      'account_title': 'My account',
      'account_email': 'Email',
      'account_not_signed_in': 'Not signed in',
      'account_plan': 'Plan',
      'account_log_out': 'Log out',
      'account_privacy': 'Privacy center',
      'access_denied_title': 'Access denied',
      'access_denied_message':
          'Your account does not have access to this area.',
      'admin_overview': 'Overview',
      'admin_users': 'Users',
      'admin_premium': 'Premium',
      'admin_catalog': 'Catalog',
      'admin_problem_requests': 'Problem requests',
      'admin_consultancy': 'Consultancy',
      'admin_content_manager': 'Content Manager',
      'admin_security_checklist': 'Security checklist',
      'admin_supabase_configured': 'Supabase configured',
      'admin_authenticated': 'Authenticated',
      'admin_rls_enabled': 'RLS-backed admin writes enabled by migration',
      'admin_anon_only': 'Client app uses the anon key only',
      'guided_selector': 'Guided selector',
      'open': 'Open',
      'cta_problem_title': 'Can’t find your problem?',
      'cta_problem_body':
          'Tell us what you need. We will review it and add it as fast as possible.',
      'cta_problem_button': 'Request a new problem',
      'cta_problem_thanks':
          'Thanks. We received your request and will review it as soon as possible.',
      'cta_consultancy_title': 'Need private help?',
      'cta_consultancy_body':
          'Premium members can request private guidance by email. Free users can request it with an extra payment when available.',
      'cta_consultancy_disclaimer':
          'UfficioFacile gives practical guidance, not legal, tax, or medical advice. Always verify final instructions on the official website or with the competent office.',
      'cta_consultancy_request': 'Request private guidance',
      'cta_consultancy_unlock': 'Unlock private guidance',
      'cta_consultancy_upgrade': 'Upgrade to Premium',
      'cta_consultancy_email': 'Send your case by email',
      'cta_payment_unavailable':
          'Premium payments are not available yet. Contact support.',
      'import_bundled_content': 'Import bundled content into CMS',
      'premium_locked_title': 'Premium guide',
      'unlock_this_guide_only': 'Unlock this guide only',
      'single_unlock_available': 'Single unlock available',
      'payment_not_active_yet': 'Payment is not active yet.',
      'upgrade_to_premium': 'Upgrade to Premium',
      'my_italy_life': 'My Italy Life',
      'checklist_progress': 'Checklist progress',
      'deadlines_short': 'Deadlines',
      'city_pack_title': 'City pack',
      'estimated_expenses': 'Estimated expenses',
      'cost_dashboard_summary':
          'Track fees, refunds, installments, and disputed amounts.',
      'category_health_asl': 'Health / ASL',
      'category_housing_rent': 'Housing / Rent',
      'category_utilities': 'Bills & Utilities',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'Internet & Phone',
      'category_public_office': 'Comune / Registry',
      'category_work_inps': 'Work / INPS',
      'category_university': 'University / Student',
      'category_general': 'General',
      'category_general_help': 'General admin help',
      'trust_title': 'Trust',
      'problem_input_placeholder':
          'Describe the problem in your own words.',
      'search_placeholder_generic': 'Search by title, tag, or description...',
      'problem_example_1': 'I want to remove Canone RAI from my bill',
      'problem_example_2': 'My gas bill is too high',
      'problem_example_3': 'I need to change my family doctor',
      'problem_example_4': 'I want to cancel internet',
      'problem_example_5': 'My landlord is not fixing the heating',
      'problem_example_6': 'I need NASpI',
      'all_label': 'All',
      'no_procedures_yet_title': 'No procedures yet',
      'no_procedures_yet_body':
          'This category does not have active procedures yet.',
      'onboarding_scope_title': 'What can UfficioFacile help with?',
      'onboarding_scope_body':
          'Bills, Canone RAI, health, rent, telecom, work, university, benefits, loans, refunds, and public-office tasks.',
      'privacy_body':
          'UfficioFacile helps you organize steps and write clearly. Always verify official rules, offices, deadlines, and eligibility before you send anything.',
      'optional_profile_setup': 'Optional profile setup',
      'full_name': 'Full name',
      'codice_fiscale': 'Codice fiscale',
      'city_label': 'City',
      'plan_title': 'Your plan',
      'plan_intro': 'Choose the level of help that fits your situation.',
      'current_plan_label': 'Current plan',
      'free_plan_label': 'Free',
      'plus_plan_label': 'Plus',
      'premium_plan_label': 'Premium',
      'one_shot_consultancy_label': 'One-shot consultancy',
      'admin_grant_label': 'Admin grant',
      'free_plan_desc':
          'Public categories, intelligent search, and basic guidance with limits.',
      'plus_plan_desc':
          'More packs, more saved requests, larger dashboards, and priority requests.',
      'premium_plan_desc':
          'All premium guides, all money-saving categories, full vaults, advanced scanner, reminders, and private help.',
      'paywall_open_plan': 'Open plans',
      'paywall_maybe_later': 'Maybe later',
      'payment_setup_message':
          'Purchase options appear when billing is configured for your workspace.',
      'already_unlocked': 'Already unlocked',
      'of_label': 'of',
      'packs_used_this_month': 'packs used this month',
    },
    'it': {
      'app_title': 'UfficioFacile',
      'hero_title':
          'Raccontaci il problema. Troviamo la procedura italiana giusta.',
      'hero_subtitle':
          'Usa parole normali: bollette, ASL, contratto di affitto, università, INPS, documenti. UfficioFacile collega il tuo problema alla categoria, ai passaggi, ai documenti e ai contatti giusti.',
      'start_problem': 'Parti dal mio problema',
      'browse_procedures': 'Esplora procedure',
      'utilities_bills': 'Bollette e utenze',
      'saved_requests': 'Richieste salvate',
      'what_help': 'Di cosa hai bisogno?',
      'onboarding_title': 'Burocrazia italiana, passo dopo passo.',
      'onboarding_subtitle':
          'Organizza procedure, promemoria, documenti e messaggi formali per bollette, affitto, sanità, università e uffici pubblici.',
      'privacy_title': 'Privacy e disclaimer',
      'skip': 'Salta',
      'next': 'Avanti',
      'done': 'Fine',
      'profile': 'Profilo',
      'help': 'Aiuto',
      'admin': 'Admin',
      'generate_pack': 'Genera pack',
      'save_request': 'Salva richiesta',
      'copied': 'Copiato',
      'request_saved': 'Richiesta salvata',
      'short_message': 'Messaggio breve',
      'email': 'Email',
      'pec': 'PEC / Formale',
      'follow_up': 'Sollecito',
      'strong_follow_up': 'Sollecito forte',
      'attachments': 'Allegati',
      'next_steps': 'Prossimi passi',
      'warnings': 'Avvisi',
      'disclaimer_short':
          'Supporto pratico per organizzazione e scrittura. Verifica sempre le istruzioni finali sul sito ufficiale o con l’ufficio competente.',
      'upcoming_reminders': 'Promemoria in arrivo',
      'requests_follow_up': 'Da sollecitare',
      'drafts': 'Bozze',
      'recent_requests': 'Richieste recenti',
      'problem_examples': 'Esempi',
      'recommendations': 'Percorsi consigliati',
      'no_results':
          'Non c’è ancora un risultato vicino. Puoi usare comunque la richiesta formale generica.',
      'compare_offers': 'Confronta offerte',
      'understand_bill': 'Capisci la bolletta',
      'canone_rai': 'Canone RAI',
      'telecom': 'Internet e telefono',
      'admin_panel': 'Pannello admin',
      'demo_data': 'Dati demo',
      'scan_situation': 'Analizza la mia situazione',
      'city_packs': 'City pack',
      'student_mode': 'Modalità studente',
      'tenant_mode': 'Modalità inquilino',
      'life_checklist': 'Checklist vita in Italia',
      'proof_folder': 'Cartella prove',
      'official_links': 'Link ufficiali',
      'cost_dashboard': 'Dashboard costi',
      'document_vault': 'Archivio documenti',
      'contacts_directory': 'Rubrica contatti',
      'calendar': 'Calendario',
      'plan': 'Piano',
      'free_plan': 'Gratis',
      'pro_plan': 'Premium',
      'consultant_plan': 'Consulente',
      'beta_access_active': 'Accesso beta attivo',
      'upgrade_to_pro': 'Passa a Premium',
      'premium_feature': 'Funzione Premium',
      'auth_account': 'Account',
      'auth_login': 'Accedi',
      'auth_create_account': 'Crea account',
      'auth_email': 'Email',
      'auth_password': 'Password',
      'auth_continue_public': 'Continua a consultare le guide pubbliche',
      'auth_login_subtitle':
          'Usa email e password per aprire il tuo spazio privato.',
      'auth_signup_subtitle':
          'Crea un account per salvare e sincronizzare richieste, promemoria e dettagli dei documenti.',
      'auth_login_or_signup': 'Accedi o crea un account',
      'auth_required_title': 'Account richiesto',
      'auth_required_message':
          'Crea un account per salvare e sincronizzare documenti, richieste e promemoria.',
      'auth_required_feature': 'Per aprire questa sezione ti serve un account.',
      'auth_wait': 'Attendi...',
      'auth_reset_password': 'Invia email per reimpostare la password',
      'auth_reset_sent':
          'Email per reimpostare la password inviata. Controlla la tua casella.',
      'auth_signup_success':
          'Account creato. Se la conferma email è attiva, conferma l’indirizzo prima di accedere.',
      'account_title': 'Il mio account',
      'account_email': 'Email',
      'account_not_signed_in': 'Non hai effettuato l’accesso',
      'account_plan': 'Piano',
      'account_log_out': 'Esci',
      'account_privacy': 'Centro privacy',
      'access_denied_title': 'Accesso negato',
      'access_denied_message':
          'Il tuo account non ha accesso a questa sezione.',
      'admin_overview': 'Panoramica',
      'admin_users': 'Utenti',
      'admin_premium': 'Premium',
      'admin_catalog': 'Catalogo',
      'admin_problem_requests': 'Richieste problema',
      'admin_consultancy': 'Consulenze',
      'admin_content_manager': 'Gestione contenuti',
      'admin_security_checklist': 'Checklist sicurezza',
      'admin_supabase_configured': 'Supabase configurato',
      'admin_authenticated': 'Autenticato',
      'admin_rls_enabled':
          'Scritture admin protette da RLS abilitate tramite migrazione',
      'admin_anon_only': 'L’app client usa solo la chiave anon',
      'guided_selector': 'Selettore guidato',
      'open': 'Apri',
      'cta_problem_title': 'Non trovi il tuo problema?',
      'cta_problem_body':
          'Raccontaci di cosa hai bisogno. Lo controlleremo e lo aggiungeremo il prima possibile.',
      'cta_problem_button': 'Richiedi un nuovo problema',
      'cta_problem_thanks':
          'Grazie. Abbiamo ricevuto la tua richiesta e la controlleremo al più presto.',
      'cta_consultancy_title': 'Hai bisogno di aiuto privato?',
      'cta_consultancy_body':
          'I membri Premium possono richiedere assistenza privata via email. Gli utenti free possono richiederla con un pagamento extra quando disponibile.',
      'cta_consultancy_disclaimer':
          'UfficioFacile offre guida pratica, non consulenza legale, fiscale o medica. Verifica sempre le istruzioni finali sul sito ufficiale o con l’ufficio competente.',
      'cta_consultancy_request': 'Richiedi assistenza privata',
      'cta_consultancy_unlock': 'Sblocca assistenza privata',
      'cta_consultancy_upgrade': 'Passa a Premium',
      'cta_consultancy_email': 'Invia il caso via email',
      'cta_payment_unavailable':
          'I pagamenti Premium non sono ancora disponibili. Contatta il supporto.',
      'import_bundled_content': 'Importa i contenuti inclusi nel CMS',
      'premium_locked_title': 'Guida Premium',
      'unlock_this_guide_only': 'Sblocca solo questa guida',
      'single_unlock_available': 'Sblocco singolo disponibile',
      'payment_not_active_yet': 'Il pagamento non è ancora attivo.',
      'upgrade_to_premium': 'Passa a Premium',
      'my_italy_life': 'La mia vita in Italia',
      'checklist_progress': 'Avanzamento checklist',
      'deadlines_short': 'Scadenze',
      'city_pack_title': 'Pacchetto città',
      'estimated_expenses': 'Spese stimate',
      'cost_dashboard_summary':
          'Controlla costi, rimborsi, rate e importi contestati.',
      'category_health_asl': 'Salute / ASL',
      'category_housing_rent': 'Casa / Affitto',
      'category_utilities': 'Bollette e utenze',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'Internet e telefono',
      'category_public_office': 'Comune / Anagrafe',
      'category_work_inps': 'Lavoro / INPS',
      'category_university': 'Università / Studenti',
      'category_general': 'Generale',
      'category_general_help': 'Aiuto amministrativo generale',
      'trust_title': 'Affidabilità',
      'problem_input_placeholder':
          'Descrivi il problema con parole tue.',
      'search_placeholder_generic':
          'Cerca per titolo, tag o descrizione...',
      'problem_example_1': 'Voglio togliere il Canone RAI dalla bolletta',
      'problem_example_2': 'La bolletta del gas è troppo alta',
      'problem_example_3': 'Devo cambiare medico di base',
      'problem_example_4': 'Voglio disdire internet',
      'problem_example_5': 'Il proprietario non aggiusta il riscaldamento',
      'problem_example_6': 'Ho bisogno della NASpI',
      'all_label': 'Tutto',
      'no_procedures_yet_title': 'Nessuna procedura disponibile',
      'no_procedures_yet_body':
          'Questa categoria non ha ancora procedure attive.',
      'onboarding_scope_title': 'Con cosa può aiutarti UfficioFacile?',
      'onboarding_scope_body':
          'Bollette, Canone RAI, sanità, affitto, telecom, lavoro, università, bonus, prestiti, rimborsi e pratiche con uffici pubblici.',
      'privacy_body':
          'UfficioFacile ti aiuta a organizzare i passaggi e scrivere in modo chiaro. Verifica sempre regole ufficiali, uffici, scadenze e requisiti prima di inviare qualcosa.',
      'optional_profile_setup': 'Profilo facoltativo',
      'full_name': 'Nome completo',
      'codice_fiscale': 'Codice fiscale',
      'city_label': 'Città',
      'plan_title': 'Il tuo piano',
      'plan_intro': 'Scegli il livello di aiuto più adatto alla tua situazione.',
      'current_plan_label': 'Piano attuale',
      'free_plan_label': 'Free',
      'plus_plan_label': 'Plus',
      'premium_plan_label': 'Premium',
      'one_shot_consultancy_label': 'Consulenza una tantum',
      'admin_grant_label': 'Concessione admin',
      'free_plan_desc':
          'Categorie pubbliche, ricerca intelligente e guide di base con limiti.',
      'plus_plan_desc':
          'Più pack, più richieste salvate, dashboard più ampie e richieste prioritarie.',
      'premium_plan_desc':
          'Tutte le guide Premium, tutte le categorie che fanno risparmiare, archivi completi, scanner avanzato, promemoria e aiuto privato.',
      'paywall_open_plan': 'Apri i piani',
      'paywall_maybe_later': 'Forse più tardi',
      'payment_setup_message':
          'Le opzioni di acquisto compaiono quando la fatturazione è configurata per il tuo workspace.',
      'already_unlocked': 'Già sbloccato',
      'of_label': 'di',
      'packs_used_this_month': 'pack usati questo mese',
    },
    'fa': {
      'app_title': 'UfficioFacile',
      'hero_title':
          'مشکل را بگو. ما روند اداری درست در ایتالیا را پیدا می‌کنیم.',
      'hero_subtitle':
          'با کلمات عادی بنویس: قبض، ASL، قرارداد اجاره، دانشگاه، INPS، مدارک. اوفیتسیو فاسیله مشکل تو را به دسته‌بندی، مراحل، مدارک و تماس‌های درست وصل می‌کند.',
      'start_problem': 'از مشکل من شروع کن',
      'browse_procedures': 'مرور فرایندها',
      'utilities_bills': 'قبض‌ها و خدمات',
      'saved_requests': 'درخواست‌های ذخیره‌شده',
      'what_help': 'در چه چیزی کمک می‌خواهید؟',
      'onboarding_title': 'کارهای اداری ایتالیا، مرحله به مرحله.',
      'onboarding_subtitle':
          'برای قبض، اجاره، درمان، دانشگاه و اداره‌های عمومی، فرایندها، یادآورها، مدارک و پیام‌های رسمی را مدیریت کنید.',
      'privacy_title': 'حریم خصوصی و توضیحات',
      'skip': 'رد کردن',
      'next': 'بعدی',
      'done': 'تمام',
      'profile': 'پروفایل',
      'help': 'راهنما',
      'admin': 'مدیر',
      'generate_pack': 'ساخت بسته',
      'save_request': 'ذخیره درخواست',
      'copied': 'کپی شد',
      'request_saved': 'درخواست ذخیره شد',
      'short_message': 'پیام کوتاه',
      'email': 'ایمیل',
      'pec': 'PEC / رسمی',
      'follow_up': 'پیگیری',
      'strong_follow_up': 'پیگیری جدی‌تر',
      'attachments': 'پیوست‌ها',
      'next_steps': 'قدم‌های بعدی',
      'warnings': 'هشدارها',
      'disclaimer_short':
          'فقط پشتیبانی عملی برای نوشتن و سازمان‌دهی. همیشه دستور نهایی را در سایت رسمی یا با اداره مربوط بررسی کنید.',
      'upcoming_reminders': 'یادآورهای پیش رو',
      'requests_follow_up': 'نیازمند پیگیری',
      'drafts': 'پیش‌نویس‌ها',
      'recent_requests': 'درخواست‌های اخیر',
      'problem_examples': 'نمونه‌ها',
      'recommendations': 'مسیرهای پیشنهادی',
      'no_results':
          'هنوز نتیجه نزدیک پیدا نشد. می‌توانید از درخواست رسمی عمومی استفاده کنید.',
      'compare_offers': 'مقایسه پیشنهادها',
      'understand_bill': 'قبض من را توضیح بده',
      'canone_rai': 'Canone RAI',
      'telecom': 'اینترنت و تلفن',
      'admin_panel': 'پنل مدیریت',
      'demo_data': 'داده آزمایشی',
      'scan_situation': 'وضعیت من را بررسی کن',
      'city_packs': 'بسته‌های شهری',
      'student_mode': 'حالت دانشجویی',
      'tenant_mode': 'حالت مستأجر',
      'life_checklist': 'چک‌لیست زندگی در ایتالیا',
      'proof_folder': 'پوشه مدارک',
      'official_links': 'لینک‌های رسمی',
      'cost_dashboard': 'داشبورد هزینه‌ها',
      'document_vault': 'آرشیو مدارک',
      'contacts_directory': 'دفترچه مخاطبان',
      'calendar': 'تقویم',
      'plan': 'پلن',
      'free_plan': 'رایگان',
      'pro_plan': 'پریمیوم',
      'consultant_plan': 'مشاور',
      'beta_access_active': 'دسترسی بتا فعال است',
      'upgrade_to_pro': 'ارتقا به پریمیوم',
      'premium_feature': 'ویژگی پریمیوم',
      'auth_account': 'حساب کاربری',
      'auth_login': 'ورود',
      'auth_create_account': 'ساخت حساب',
      'auth_email': 'ایمیل',
      'auth_password': 'رمز عبور',
      'auth_continue_public': 'ادامه مرور راهنماهای عمومی',
      'auth_login_subtitle': 'با ایمیل و رمز عبور وارد فضای خصوصی خود شوید.',
      'auth_signup_subtitle':
          'برای ذخیره و همگام‌سازی درخواست‌ها، یادآورها و جزئیات مدارک حساب بسازید.',
      'auth_login_or_signup': 'ورود یا ساخت حساب',
      'auth_required_title': 'حساب لازم است',
      'auth_required_message':
          'برای ذخیره و همگام‌سازی مدارک، درخواست‌ها و یادآورها حساب بسازید.',
      'auth_required_feature': 'برای باز کردن این بخش به حساب نیاز دارید.',
      'auth_wait': 'لطفاً صبر کنید...',
      'auth_reset_password': 'ایمیل بازنشانی رمز عبور را ارسال کن',
      'auth_reset_sent':
          'ایمیل بازنشانی رمز عبور ارسال شد. صندوق ورودی را بررسی کنید.',
      'auth_signup_success':
          'حساب ساخته شد. اگر تأیید ایمیل فعال باشد، قبل از ورود ایمیل خود را تأیید کنید.',
      'account_title': 'حساب من',
      'account_email': 'ایمیل',
      'account_not_signed_in': 'وارد نشده‌اید',
      'account_plan': 'پلن',
      'account_log_out': 'خروج',
      'account_privacy': 'مرکز حریم خصوصی',
      'access_denied_title': 'دسترسی مجاز نیست',
      'access_denied_message': 'حساب شما به این بخش دسترسی ندارد.',
      'admin_overview': 'نمای کلی',
      'admin_users': 'کاربران',
      'admin_premium': 'پریمیوم',
      'admin_catalog': 'کاتالوگ',
      'admin_problem_requests': 'درخواست‌های مشکل',
      'admin_consultancy': 'مشاوره',
      'admin_content_manager': 'مدیریت محتوا',
      'admin_security_checklist': 'چک‌لیست امنیت',
      'admin_supabase_configured': 'Supabase پیکربندی شده است',
      'admin_authenticated': 'احراز هویت شده',
      'admin_rls_enabled': 'نوشتن‌های مدیریتی با RLS محافظت می‌شوند',
      'admin_anon_only': 'برنامه فقط از کلید anon در سمت کاربر استفاده می‌کند',
      'guided_selector': 'انتخاب‌گر مرحله‌ای',
      'open': 'باز کردن',
      'cta_problem_title': 'مشکل شما اینجا نیست؟',
      'cta_problem_body':
          'آنچه نیاز دارید را برای ما بفرستید. بررسی می‌کنیم و هرچه سریع‌تر اضافه می‌کنیم.',
      'cta_problem_button': 'ثبت مشکل جدید',
      'cta_problem_thanks':
          'ممنون. درخواست شما دریافت شد و خیلی زود بررسی می‌شود.',
      'cta_consultancy_title': 'به کمک خصوصی نیاز دارید؟',
      'cta_consultancy_body':
          'اعضای پریمیوم می‌توانند راهنمایی خصوصی ایمیلی بگیرند. کاربران رایگان در صورت فعال بودن پرداخت اضافه می‌توانند درخواست بدهند.',
      'cta_consultancy_disclaimer':
          'UfficioFacile راهنمای عملی ارائه می‌دهد، نه مشاوره حقوقی، مالیاتی یا پزشکی. همیشه دستور نهایی را در سایت رسمی یا با اداره مربوط بررسی کنید.',
      'cta_consultancy_request': 'درخواست راهنمایی خصوصی',
      'cta_consultancy_unlock': 'فعال‌سازی راهنمایی خصوصی',
      'cta_consultancy_upgrade': 'ارتقا به پریمیوم',
      'cta_consultancy_email': 'ارسال پرونده با ایمیل',
      'cta_payment_unavailable':
          'پرداخت‌های پریمیوم هنوز فعال نیستند. با پشتیبانی تماس بگیرید.',
      'import_bundled_content': 'وارد کردن محتوای پیش‌فرض به CMS',
      'premium_locked_title': 'راهنمای پریمیوم',
      'unlock_this_guide_only': 'فقط همین راهنما را باز کن',
      'single_unlock_available': 'باز کردن تکی موجود است',
      'payment_not_active_yet': 'پرداخت هنوز فعال نیست.',
      'upgrade_to_premium': 'ارتقا به پریمیوم',
      'my_italy_life': 'زندگی من در ایتالیا',
      'checklist_progress': 'پیشرفت چک‌لیست',
      'deadlines_short': 'مهلت‌ها',
      'city_pack_title': 'بسته شهر',
      'estimated_expenses': 'هزینه‌های تخمینی',
      'cost_dashboard_summary':
          'کارمزدها، بازپرداخت‌ها، قسط‌ها و مبالغ مورد اختلاف را پیگیری کن.',
      'category_health_asl': 'سلامت / ASL',
      'category_housing_rent': 'خانه / اجاره',
      'category_utilities': 'قبض‌ها و خدمات',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'اینترنت و تلفن',
      'category_public_office': 'Comune / ثبت احوال',
      'category_work_inps': 'کار / INPS',
      'category_university': 'دانشگاه / دانشجو',
      'category_general': 'عمومی',
      'category_general_help': 'راهنمای اداری عمومی',
      'trust_title': 'اعتماد',
      'problem_input_placeholder': 'مشکل را با زبان خودت توضیح بده.',
      'search_placeholder_generic':
          'بر اساس عنوان، برچسب یا توضیح جستجو کن...',
      'problem_example_1': 'می‌خواهم Canone RAI را از قبض حذف کنم',
      'problem_example_2': 'قبض گاز خیلی زیاد است',
      'problem_example_3': 'باید پزشک خانواده را عوض کنم',
      'problem_example_4': 'می‌خواهم اینترنت را لغو کنم',
      'problem_example_5': 'صاحبخانه گرمایش را تعمیر نمی‌کند',
      'problem_example_6': 'به NASpI نیاز دارم',
      'all_label': 'همه',
      'no_procedures_yet_title': 'هنوز فرایندی نیست',
      'no_procedures_yet_body':
          'هنوز هیچ فرایند فعالی در این دسته وجود ندارد.',
      'onboarding_scope_title': 'UfficioFacile در چه چیزهایی کمک می‌کند؟',
      'onboarding_scope_body':
          'قبض‌ها، Canone RAI، درمان، اجاره، مخابرات، کار، دانشگاه، بونوس‌ها، وام‌ها، بازپرداخت‌ها و کارهای اداری با اداره‌های عمومی.',
      'privacy_body':
          'UfficioFacile به تو کمک می‌کند مراحل را مرتب کنی و واضح بنویسی. قبل از ارسال هر چیزی، همیشه قوانین رسمی، اداره مربوط، مهلت‌ها و شرایط را بررسی کن.',
      'optional_profile_setup': 'تنظیم اختیاری پروفایل',
      'full_name': 'نام کامل',
      'codice_fiscale': 'Codice fiscale',
      'city_label': 'شهر',
      'plan_title': 'پلن شما',
      'plan_intro': 'سطح کمکی را انتخاب کن که با وضعیت تو هماهنگ باشد.',
      'current_plan_label': 'پلن فعلی',
      'free_plan_label': 'رایگان',
      'plus_plan_label': 'پلاس',
      'premium_plan_label': 'پریمیوم',
      'one_shot_consultancy_label': 'مشاوره یک‌باره',
      'admin_grant_label': 'امتیاز مدیریتی',
      'free_plan_desc':
          'دسته‌های عمومی، جستجوی هوشمند و راهنمای پایه با محدودیت.',
      'plus_plan_desc':
          'بسته‌های بیشتر، درخواست‌های ذخیره‌شده بیشتر، داشبوردهای بزرگ‌تر و درخواست‌های اولویت‌دار.',
      'premium_plan_desc':
          'همه راهنماهای پریمیوم، همه دسته‌های صرفه‌جویی مالی، آرشیو کامل، اسکن پیشرفته، یادآورها و کمک خصوصی.',
      'paywall_open_plan': 'دیدن پلن‌ها',
      'paywall_maybe_later': 'بعداً',
      'payment_setup_message':
          'وقتی پرداخت برای این محیط فعال شود، گزینه‌های خرید اینجا نمایش داده می‌شوند.',
      'already_unlocked': 'قبلاً باز شده',
      'of_label': 'از',
      'packs_used_this_month': 'بسته استفاده شده در این ماه',
    },
    'fr': {
      'app_title': 'UfficioFacile',
      'hero_title':
          'Dites-nous le problème. Nous trouvons la bonne démarche italienne.',
      'hero_subtitle':
          'Utilisez des mots simples : factures, ASL, bail, université, INPS, documents. UfficioFacile relie votre besoin à la bonne catégorie, aux étapes, aux documents et aux contacts utiles.',
      'start_problem': 'Partir de mon problème',
      'browse_procedures': 'Parcourir les démarches',
      'utilities_bills': 'Factures et contrats',
      'saved_requests': 'Demandes enregistrées',
      'what_help': 'De quoi avez-vous besoin ?',
      'onboarding_title': 'Les démarches italiennes, étape par étape.',
      'onboarding_subtitle':
          'Organisez vos démarches, rappels, documents et messages formels pour les factures, le logement, la santé, l’université et les bureaux publics.',
      'privacy_title': 'Confidentialité et avertissement',
      'skip': 'Passer',
      'next': 'Suivant',
      'done': 'Terminé',
      'profile': 'Profil',
      'help': 'Aide',
      'admin': 'Admin',
      'generate_pack': 'Générer le pack',
      'save_request': 'Enregistrer la demande',
      'copied': 'Copié',
      'request_saved': 'Demande enregistrée',
      'short_message': 'Message court',
      'email': 'Email',
      'pec': 'PEC / Formel',
      'follow_up': 'Relance',
      'strong_follow_up': 'Relance formelle',
      'attachments': 'Pièces jointes',
      'next_steps': 'Prochaines étapes',
      'warnings': 'Points d’attention',
      'disclaimer_short':
          'Aide pratique à la rédaction et à l’organisation uniquement. Vérifiez toujours les instructions finales sur le site officiel ou auprès du bureau compétent.',
      'upcoming_reminders': 'Rappels à venir',
      'requests_follow_up': 'À relancer',
      'drafts': 'Brouillons',
      'recent_requests': 'Demandes récentes',
      'problem_examples': 'Exemples',
      'recommendations': 'Parcours recommandés',
      'no_results':
          'Aucun résultat proche pour le moment. Vous pouvez quand même utiliser la demande formelle générale.',
      'compare_offers': 'Comparer les offres',
      'understand_bill': 'Comprendre ma facture',
      'canone_rai': 'Canone RAI',
      'telecom': 'Internet et téléphone',
      'admin_panel': 'Panneau admin',
      'demo_data': 'Données de démonstration',
      'scan_situation': 'Analyser ma situation',
      'city_packs': 'Packs ville',
      'student_mode': 'Mode étudiant',
      'tenant_mode': 'Mode locataire',
      'life_checklist': 'Ma checklist Italie',
      'proof_folder': 'Dossier de preuves',
      'official_links': 'Liens officiels',
      'cost_dashboard': 'Tableau des coûts',
      'document_vault': 'Coffre de documents',
      'contacts_directory': 'Répertoire de contacts',
      'calendar': 'Calendrier',
      'plan': 'Offre',
      'free_plan': 'Gratuit',
      'pro_plan': 'Premium',
      'consultant_plan': 'Consultant',
      'beta_access_active': 'Accès bêta actif',
      'upgrade_to_pro': 'Passer à Premium',
      'premium_feature': 'Fonction Premium',
      'auth_account': 'Compte',
      'auth_login': 'Se connecter',
      'auth_create_account': 'Créer un compte',
      'auth_email': 'Email',
      'auth_password': 'Mot de passe',
      'auth_continue_public': 'Continuer à parcourir les guides publics',
      'auth_login_subtitle':
          'Utilisez votre email et votre mot de passe pour ouvrir votre espace privé.',
      'auth_signup_subtitle':
          'Créez un compte pour enregistrer et synchroniser vos demandes, rappels et détails de documents.',
      'auth_login_or_signup': 'Se connecter ou créer un compte',
      'auth_required_title': 'Compte requis',
      'auth_required_message':
          'Créez un compte pour enregistrer et synchroniser vos documents, demandes et rappels.',
      'auth_required_feature':
          'Vous avez besoin d’un compte pour ouvrir cette section.',
      'auth_wait': 'Veuillez patienter...',
      'auth_reset_password': 'Envoyer un email de réinitialisation',
      'auth_reset_sent':
          'Email de réinitialisation envoyé. Vérifiez votre boîte de réception.',
      'auth_signup_success':
          'Compte créé. Si la confirmation par email est active, confirmez votre adresse avant de vous connecter.',
      'account_title': 'Mon compte',
      'account_email': 'Email',
      'account_not_signed_in': 'Non connecté',
      'account_plan': 'Offre',
      'account_log_out': 'Se déconnecter',
      'account_privacy': 'Centre de confidentialité',
      'access_denied_title': 'Accès refusé',
      'access_denied_message': 'Votre compte n’a pas accès à cette section.',
      'admin_overview': 'Vue d’ensemble',
      'admin_users': 'Utilisateurs',
      'admin_premium': 'Premium',
      'admin_catalog': 'Catalogue',
      'admin_problem_requests': 'Demandes de problème',
      'admin_consultancy': 'Consultations',
      'admin_content_manager': 'Gestionnaire de contenu',
      'admin_security_checklist': 'Checklist sécurité',
      'admin_supabase_configured': 'Supabase configuré',
      'admin_authenticated': 'Authentifié',
      'admin_rls_enabled': 'Écritures admin protégées par RLS via migration',
      'admin_anon_only': 'L’application cliente utilise uniquement la clé anon',
      'guided_selector': 'Sélecteur guidé',
      'open': 'Ouvrir',
      'cta_problem_title': 'Vous ne trouvez pas votre problème ?',
      'cta_problem_body':
          'Dites-nous ce dont vous avez besoin. Nous le vérifierons et l’ajouterons aussi vite que possible.',
      'cta_problem_button': 'Demander un nouveau problème',
      'cta_problem_thanks':
          'Merci. Nous avons reçu votre demande et nous allons l’examiner rapidement.',
      'cta_consultancy_title': 'Besoin d’une aide privée ?',
      'cta_consultancy_body':
          'Les membres Premium peuvent demander une aide privée par email. Les utilisateurs gratuits peuvent la demander avec un paiement supplémentaire quand il est disponible.',
      'cta_consultancy_disclaimer':
          'UfficioFacile fournit une aide pratique, pas un conseil juridique, fiscal ou médical. Vérifiez toujours les instructions finales sur le site officiel ou auprès du bureau compétent.',
      'cta_consultancy_request': 'Demander une aide privée',
      'cta_consultancy_unlock': 'Débloquer l’aide privée',
      'cta_consultancy_upgrade': 'Passer à Premium',
      'cta_consultancy_email': 'Envoyer mon dossier par email',
      'cta_payment_unavailable':
          'Les paiements Premium ne sont pas encore disponibles. Contactez le support.',
      'import_bundled_content': 'Importer le contenu intégré dans le CMS',
      'premium_locked_title': 'Guide Premium',
      'unlock_this_guide_only': 'Débloquer ce guide seulement',
      'single_unlock_available': 'Déblocage unique disponible',
      'payment_not_active_yet': 'Le paiement n’est pas encore actif.',
      'upgrade_to_premium': 'Passer à Premium',
      'my_italy_life': 'Ma vie en Italie',
      'checklist_progress': 'Progression de la checklist',
      'deadlines_short': 'Délais',
      'city_pack_title': 'Pack ville',
      'estimated_expenses': 'Dépenses estimées',
      'cost_dashboard_summary':
          'Suivez les frais, remboursements, mensualités et montants contestés.',
      'category_health_asl': 'Santé / ASL',
      'category_housing_rent': 'Logement / Loyer',
      'category_utilities': 'Factures et contrats',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'Internet et téléphone',
      'category_public_office': 'Commune / Registre',
      'category_work_inps': 'Travail / INPS',
      'category_university': 'Université / Étudiant',
      'category_general': 'Général',
      'category_general_help': 'Aide administrative générale',
      'trust_title': 'Confiance',
      'problem_input_placeholder':
          'Décrivez le problème avec vos propres mots.',
      'search_placeholder_generic':
          'Chercher par titre, tag ou description...',
      'problem_example_1':
          'Je veux retirer le Canone RAI de ma facture',
      'problem_example_2': 'Ma facture de gaz est trop élevée',
      'problem_example_3': 'Je dois changer de médecin traitant',
      'problem_example_4': 'Je veux résilier internet',
      'problem_example_5':
          'Mon propriétaire ne répare pas le chauffage',
      'problem_example_6': 'J’ai besoin de la NASpI',
      'all_label': 'Tout',
      'no_procedures_yet_title': 'Aucune démarche pour le moment',
      'no_procedures_yet_body':
          'Cette catégorie ne contient pas encore de démarches actives.',
      'onboarding_scope_title': 'Avec quoi UfficioFacile peut vous aider ?',
      'onboarding_scope_body':
          'Factures, Canone RAI, santé, logement, télécoms, travail, université, aides, prêts, remboursements et démarches auprès des bureaux publics.',
      'privacy_body':
          'UfficioFacile vous aide à organiser les étapes et à écrire clairement. Vérifiez toujours les règles officielles, les bureaux, les délais et les conditions avant tout envoi.',
      'optional_profile_setup': 'Profil facultatif',
      'full_name': 'Nom complet',
      'codice_fiscale': 'Codice fiscale',
      'city_label': 'Ville',
      'plan_title': 'Votre offre',
      'plan_intro': 'Choisissez le niveau d’aide qui convient à votre situation.',
      'current_plan_label': 'Offre actuelle',
      'free_plan_label': 'Gratuit',
      'plus_plan_label': 'Plus',
      'premium_plan_label': 'Premium',
      'one_shot_consultancy_label': 'Consultation ponctuelle',
      'admin_grant_label': 'Attribution admin',
      'free_plan_desc':
          'Catégories publiques, recherche intelligente et guides de base avec limites.',
      'plus_plan_desc':
          'Plus de packs, plus de demandes enregistrées, tableaux élargis et demandes prioritaires.',
      'premium_plan_desc':
          'Tous les guides Premium, toutes les catégories qui font économiser, coffres complets, scanner avancé, rappels et aide privée.',
      'paywall_open_plan': 'Voir les offres',
      'paywall_maybe_later': 'Plus tard',
      'payment_setup_message':
          'Les options d’achat apparaissent quand la facturation est configurée pour votre espace.',
      'already_unlocked': 'Déjà débloqué',
      'of_label': 'sur',
      'packs_used_this_month': 'packs utilisés ce mois-ci',
    },
    'es': {
      'app_title': 'UfficioFacile',
      'hero_title':
          'Cuéntanos el problema. Encontramos el trámite italiano correcto.',
      'hero_subtitle':
          'Usa palabras normales: facturas, ASL, contrato de alquiler, universidad, INPS, documentos. UfficioFacile conecta tu problema con la categoría, los pasos, los documentos y los contactos correctos.',
      'start_problem': 'Empezar por mi problema',
      'browse_procedures': 'Explorar trámites',
      'utilities_bills': 'Facturas y servicios',
      'saved_requests': 'Solicitudes guardadas',
      'what_help': '¿En qué necesitas ayuda?',
      'scan_situation': 'Analizar mi situación',
      'document_vault': 'Archivo de documentos',
      'contacts_directory': 'Directorio de contactos',
      'official_links': 'Enlaces oficiales',
      'cost_dashboard': 'Panel de costes',
      'premium_locked_title': 'Guía Premium',
      'unlock_this_guide_only': 'Desbloquear solo esta guía',
      'single_unlock_available': 'Desbloqueo único disponible',
      'payment_not_active_yet': 'El pago todavía no está activo.',
      'upgrade_to_premium': 'Pasar a Premium',
      'my_italy_life': 'Mi vida en Italia',
      'checklist_progress': 'Progreso de la lista',
      'deadlines_short': 'Plazos',
      'city_pack_title': 'Paquete de ciudad',
      'estimated_expenses': 'Gastos estimados',
      'cost_dashboard_summary':
          'Sigue tasas, reembolsos, cuotas e importes en disputa.',
      'category_health_asl': 'Salud / ASL',
      'category_housing_rent': 'Vivienda / Alquiler',
      'category_utilities': 'Facturas y servicios',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'Internet y teléfono',
      'category_public_office': 'Comune / Registro',
      'category_work_inps': 'Trabajo / INPS',
      'category_university': 'Universidad / Estudiante',
      'category_general': 'General',
      'category_general_help': 'Ayuda administrativa general',
      'trust_title': 'Confianza',
      'problem_input_placeholder':
          'Describe el problema con tus propias palabras.',
      'search_placeholder_generic':
          'Buscar por título, etiqueta o descripción...',
      'problem_example_1': 'Quiero quitar el Canone RAI de mi factura',
      'problem_example_2': 'Mi factura de gas es demasiado alta',
      'problem_example_3': 'Necesito cambiar de médico de cabecera',
      'problem_example_4': 'Quiero cancelar internet',
      'problem_example_5': 'Mi casero no arregla la calefacción',
      'problem_example_6': 'Necesito la NASpI',
      'all_label': 'Todo',
      'no_procedures_yet_title': 'Todavía no hay trámites',
      'no_procedures_yet_body':
          'Esta categoría todavía no tiene trámites activos.',
      'onboarding_scope_title': '¿Con qué puede ayudarte UfficioFacile?',
      'onboarding_scope_body':
          'Facturas, Canone RAI, salud, alquiler, telecomunicaciones, trabajo, universidad, ayudas, préstamos, reembolsos y gestiones con oficinas públicas.',
      'privacy_title': 'Privacidad y aviso',
      'privacy_body':
          'UfficioFacile te ayuda a organizar los pasos y escribir con claridad. Verifica siempre las reglas oficiales, las oficinas, los plazos y los requisitos antes de enviar algo.',
      'optional_profile_setup': 'Perfil opcional',
      'full_name': 'Nombre completo',
      'codice_fiscale': 'Codice fiscale',
      'city_label': 'Ciudad',
      'auth_email': 'Correo electrónico',
      'plan_title': 'Tu plan',
      'plan_intro': 'Elige el nivel de ayuda que mejor se adapte a tu situación.',
      'current_plan_label': 'Plan actual',
      'free_plan_label': 'Gratis',
      'plus_plan_label': 'Plus',
      'premium_plan_label': 'Premium',
      'one_shot_consultancy_label': 'Consultoría puntual',
      'admin_grant_label': 'Concesión admin',
      'free_plan_desc':
          'Categorías públicas, búsqueda inteligente y guías básicas con límites.',
      'plus_plan_desc':
          'Más packs, más solicitudes guardadas, paneles ampliados y solicitudes prioritarias.',
      'premium_plan_desc':
          'Todas las guías Premium, todas las categorías para ahorrar dinero, archivos completos, escáner avanzado, recordatorios y ayuda privada.',
      'paywall_open_plan': 'Ver planes',
      'paywall_maybe_later': 'Quizá más tarde',
      'payment_setup_message':
          'Las opciones de compra aparecen cuando la facturación está configurada para tu espacio.',
      'already_unlocked': 'Ya desbloqueado',
      'of_label': 'de',
      'packs_used_this_month': 'packs usados este mes',
    },
    'ar': {
      'app_title': 'UfficioFacile',
      'hero_title': 'اشرح لنا المشكلة. وسنجد لك الإجراء الإيطالي المناسب.',
      'hero_subtitle':
          'استخدم كلمات عادية: فواتير، ASL، عقد إيجار، جامعة، INPS، مستندات. يربط UfficioFacile مشكلتك بالفئة والخطوات والمستندات وجهات الاتصال المناسبة.',
      'start_problem': 'ابدأ من مشكلتي',
      'browse_procedures': 'تصفح الإجراءات',
      'utilities_bills': 'الفواتير والخدمات',
      'saved_requests': 'الطلبات المحفوظة',
      'what_help': 'ما الذي تحتاج إلى مساعدة فيه؟',
      'scan_situation': 'افحص وضعي',
      'document_vault': 'أرشيف المستندات',
      'contacts_directory': 'دليل جهات الاتصال',
      'official_links': 'الروابط الرسمية',
      'cost_dashboard': 'لوحة التكاليف',
      'premium_locked_title': 'دليل Premium',
      'unlock_this_guide_only': 'افتح هذا الدليل فقط',
      'single_unlock_available': 'فتح منفرد متاح',
      'payment_not_active_yet': 'الدفع غير مفعل بعد.',
      'upgrade_to_premium': 'الترقية إلى Premium',
      'my_italy_life': 'حياتي في إيطاليا',
      'checklist_progress': 'تقدم القائمة',
      'deadlines_short': 'المواعيد',
      'city_pack_title': 'حزمة المدينة',
      'estimated_expenses': 'المصاريف المقدرة',
      'cost_dashboard_summary':
          'تابع الرسوم والاستردادات والأقساط والمبالغ المتنازع عليها.',
      'category_health_asl': 'الصحة / ASL',
      'category_housing_rent': 'السكن / الإيجار',
      'category_utilities': 'الفواتير والخدمات',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'الإنترنت والهاتف',
      'category_public_office': 'البلدية / السجل',
      'category_work_inps': 'العمل / INPS',
      'category_university': 'الجامعة / الطالب',
      'category_general': 'عام',
      'category_general_help': 'مساعدة إدارية عامة',
      'trust_title': 'الثقة',
      'problem_input_placeholder': 'اشرح المشكلة بكلماتك.',
      'search_placeholder_generic':
          'ابحث حسب العنوان أو الوسم أو الوصف...',
      'problem_example_1': 'أريد إزالة Canone RAI من الفاتورة',
      'problem_example_2': 'فاتورة الغاز مرتفعة جداً',
      'problem_example_3': 'أحتاج إلى تغيير طبيب الأسرة',
      'problem_example_4': 'أريد إلغاء الإنترنت',
      'problem_example_5': 'المالك لا يصلح التدفئة',
      'problem_example_6': 'أحتاج إلى NASpI',
      'all_label': 'الكل',
      'no_procedures_yet_title': 'لا توجد إجراءات بعد',
      'no_procedures_yet_body':
          'لا تحتوي هذه الفئة على إجراءات نشطة حتى الآن.',
      'onboarding_scope_title': 'في ماذا يمكن أن يساعدك UfficioFacile؟',
      'onboarding_scope_body':
          'الفواتير، Canone RAI، الصحة، الإيجار، الاتصالات، العمل، الجامعة، المساعدات، القروض، الاستردادات، والمعاملات مع الجهات العامة.',
      'privacy_title': 'الخصوصية والتنبيه',
      'privacy_body':
          'يساعدك UfficioFacile على ترتيب الخطوات والكتابة بوضوح. تحقق دائماً من القواعد الرسمية والجهات والمواعيد والشروط قبل إرسال أي شيء.',
      'optional_profile_setup': 'إعداد ملف شخصي اختياري',
      'full_name': 'الاسم الكامل',
      'codice_fiscale': 'الرمز الضريبي',
      'city_label': 'المدينة',
      'auth_email': 'البريد الإلكتروني',
      'plan_title': 'خطتك',
      'plan_intro': 'اختر مستوى المساعدة المناسب لوضعك.',
      'current_plan_label': 'الخطة الحالية',
      'free_plan_label': 'مجاني',
      'plus_plan_label': 'Plus',
      'premium_plan_label': 'Premium',
      'one_shot_consultancy_label': 'استشارة لمرة واحدة',
      'admin_grant_label': 'منحة إدارية',
      'free_plan_desc':
          'فئات عامة وبحث ذكي وإرشاد أساسي مع حدود استخدام.',
      'plus_plan_desc':
          'حزم أكثر، طلبات محفوظة أكثر، لوحات أكبر، وطلبات ذات أولوية.',
      'premium_plan_desc':
          'جميع الأدلة المميزة، كل الفئات التي تساعد على التوفير، أرشيفات كاملة، فحص متقدم، تذكيرات، ومساعدة خاصة.',
      'paywall_open_plan': 'عرض الخطط',
      'paywall_maybe_later': 'ربما لاحقاً',
      'payment_setup_message':
          'تظهر خيارات الشراء عندما يتم تفعيل الفوترة لمساحة العمل الخاصة بك.',
      'already_unlocked': 'مفتوح بالفعل',
      'of_label': 'من',
      'packs_used_this_month': 'حزم مستخدمة هذا الشهر',
    },
  };
}

class AppLocalizationsScope extends InheritedWidget {
  const AppLocalizationsScope({
    super.key,
    required this.localizations,
    required super.child,
  });

  final AppLocalizations localizations;

  static AppLocalizations of(BuildContext context) {
    final scope = context
        .dependOnInheritedWidgetOfExactType<AppLocalizationsScope>();
    assert(scope != null, 'AppLocalizationsScope not found');
    return scope!.localizations;
  }

  @override
  bool updateShouldNotify(AppLocalizationsScope oldWidget) {
    return oldWidget.localizations.languageCode != localizations.languageCode;
  }
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizationsScope.of(this);
}
