import 'package:flutter/material.dart';

import 'localized_text.dart';

class AppLocalizations {
  AppLocalizations(this.languageCode);

  final String languageCode;

  static const supportedLocales = [
    Locale('en'),
    Locale('it'),
    Locale('fr'),
    Locale('es'),
    Locale('fa'),
    Locale('ar'),
  ];

  static const rtlLanguages = {'fa', 'ar'};

  bool get isRtl => rtlLanguages.contains(languageCode);

  static Map<String, Map<String, String>> get localizedValues =>
      _localizedValues;

  String t(String key) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        _localizedValues['it']?[key] ??
        key;
  }

  String localizedMap(Map<String, dynamic> values, {String fallback = ''}) {
    return resolveLocalizedText(values, languageCode, fallback: fallback);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'UfficioFacile',
      'hero_title':
          'Tell us the problem. We’ll find the right Italian procedure.',
      'hero_subtitle':
          'Use normal words: bills, ASL, rent contract, university, INPS, documents. UfficioFacile matches your issue with the right category, steps, documents, and contacts.',
      'start_problem': 'Start from my problem',
      'browse_procedures': 'Browse procedures',
      'utilities_bills': 'Bills and utilities',
      'saved_requests': 'Saved requests',
      'what_help': 'What do you need help with?',
      'onboarding_title': 'Italian admin, step by step.',
      'onboarding_subtitle':
          'Organize procedures, reminders, documents, and formal messages for bills, rent, health, university, and public offices.',
      'onboarding_demo_title': 'UfficioFacile',
      'onboarding_demo_subtitle':
          'Handle Italian bureaucracy without getting lost.',
      'onboarding_card_1_title': 'Find the right procedure',
      'onboarding_card_1_body':
          'Choose a category and see what to do, where to go, and which documents you need.',
      'onboarding_card_2_title': 'Use verified contacts',
      'onboarding_card_2_body':
          'Get official links, offices, PEC addresses, emails, and forms when available.',
      'onboarding_card_3_title': 'Unlock premium help',
      'onboarding_card_3_body':
          'Save time with deeper guides, request missing problems, and get private support.',
      'privacy_title': 'Privacy and disclaimer',
      'skip': 'Skip',
      'next': 'Next',
      'done': 'Done',
      'profile': 'Profile',
      'profile_full_name': 'Full name',
      'profile_codice_fiscale': 'Codice fiscale',
      'profile_city': 'City',
      'profile_language': 'Language',
      'profile_backend_mode': 'Backend mode',
      'profile_backend_supabase': 'Supabase sync is active',
      'profile_backend_local': 'Local-only mode',
      'profile_save': 'Save profile',
      'profile_saving': 'Saving profile...',
      'profile_saved': 'Profile saved',
      'profile_save_failed': 'We could not save your profile right now.',
      'profile_sync_settings': 'Sync settings',
      'help': 'Help',
      'admin': 'Admin',
      'generate_pack': 'Generate pack',
      'save_request': 'Save request',
      'copied': 'Copied',
      'request_saved': 'Request saved',
      'short_message': 'Short message',
      'email': 'Email',
      'pec': 'PEC / Formal',
      'follow_up': 'Follow-up',
      'strong_follow_up': 'Stronger follow-up',
      'attachments': 'Attachments',
      'next_steps': 'Next steps',
      'warnings': 'Warnings',
      'disclaimer_short':
          'Practical drafting and organization support only. Always verify the final instructions on the official website or with the competent office.',
      'upcoming_reminders': 'Upcoming reminders',
      'requests_follow_up': 'Needs follow-up',
      'drafts': 'Drafts',
      'recent_requests': 'Recent requests',
      'problem_examples': 'Examples',
      'recommendations': 'Recommended workflows',
      'no_results':
          'No close match yet. You can still use the general formal request.',
      'compare_offers': 'Compare offers',
      'understand_bill': 'Understand my bill',
      'canone_rai': 'Canone RAI',
      'telecom': 'Internet and phone',
      'admin_panel': 'Admin panel',
      'demo_data': 'Sample data',
      'scan_situation': 'Scan my situation',
      'city_packs': 'City packs',
      'student_mode': 'Student mode',
      'tenant_mode': 'Tenant mode',
      'life_checklist': 'My Italy checklist',
      'proof_folder': 'Proof folder',
      'official_links': 'Official links',
      'cost_dashboard': 'Cost dashboard',
      'document_vault': 'Document vault',
      'contacts_directory': 'Contacts directory',
      'calendar': 'Calendar',
      'plan': 'Plan',
      'free_plan': 'Free',
      'pro_plan': 'Premium',
      'consultant_plan': 'Consultancy',
      'beta_access_active': 'Paid access active',
      'upgrade_to_pro': 'Upgrade to Premium',
      'premium_feature': 'Premium feature',
      'auth_account': 'Account',
      'auth_login': 'Log in',
      'auth_create_account': 'Create account',
      'auth_email': 'Email',
      'auth_password': 'Password',
      'auth_continue_public': 'Continue browsing public guides',
      'auth_login_subtitle':
          'Use your email and password to open your private workspace.',
      'auth_signup_subtitle':
          'Create an account to save and sync your requests, reminders, and document details.',
      'auth_login_or_signup': 'Log in or create account',
      'auth_required_title': 'Account required',
      'auth_required_message':
          'Create an account to save and sync your documents, requests, and reminders.',
      'auth_required_feature': 'You need an account to open this area.',
      'auth_wait': 'Please wait...',
      'auth_reset_password': 'Send password reset email',
      'auth_reset_sent': 'Password reset email sent. Check your inbox.',
      'auth_signup_success':
          'Account created. If email confirmation is enabled, confirm your email before signing in.',
      'account_title': 'My account',
      'account_email': 'Email',
      'account_not_signed_in': 'Not signed in',
      'account_plan': 'Plan',
      'account_log_out': 'Log out',
      'signed_out': 'Signed out',
      'account_privacy': 'Privacy center',
      'account_delete': 'Delete account',
      'access_denied_title': 'Access denied',
      'access_denied_message':
          'Your account does not have access to this area.',
      'admin_overview': 'Overview',
      'admin_users': 'Users',
      'admin_premium': 'Premium',
      'admin_catalog': 'Catalog',
      'admin_problem_requests': 'Problem requests',
      'admin_consultancy': 'Consultancy',
      'admin_content_manager': 'Content Manager',
      'admin_security_checklist': 'Security checklist',
      'admin_supabase_configured': 'Supabase configured',
      'admin_authenticated': 'Authenticated',
      'admin_rls_enabled': 'RLS-backed admin writes enabled by migration',
      'admin_anon_only': 'Client app uses the anon key only',
      'guided_selector': 'Guided selector',
      'open': 'Open',
      'cta_problem_title': 'Can’t find your problem?',
      'cta_problem_body':
          'Tell us what you need. We will review it and add it as fast as possible.',
      'cta_problem_button': 'Request a new problem',
      'cta_problem_thanks':
          'Thanks. We received your request and will review it as soon as possible.',
      'cta_consultancy_title': 'Need private help?',
      'cta_consultancy_body':
          'Premium members can request private guidance by email. Free users can request it with an extra payment when available.',
      'cta_consultancy_disclaimer':
          'UfficioFacile gives practical guidance, not legal, tax, or medical advice. Always verify final instructions on the official website or with the competent office.',
      'cta_consultancy_request': 'Request private guidance',
      'cta_consultancy_unlock': 'Unlock private guidance',
      'cta_consultancy_upgrade': 'Upgrade to Premium',
      'cta_consultancy_email': 'Send your case by email',
      'cta_payment_unavailable':
          'Premium payments are not available yet. Contact support.',
      'import_bundled_content': 'Import bundled content into CMS',
      'premium_locked_title': 'Premium guide',
      'unlock_this_guide_only': 'Unlock this guide only',
      'single_unlock_available': 'Single unlock available',
      'payment_not_active_yet': 'Payment is not active yet.',
      'upgrade_to_premium': 'Upgrade to Premium',
      'my_italy_life': 'My Italy Life',
      'checklist_progress': 'Checklist progress',
      'deadlines_short': 'Deadlines',
      'city_pack_title': 'City pack',
      'city_catalog_label': 'Catalog city',
      'city_catalog_chip_prefix': 'City',
      'city_catalog_selector': 'Guide city',
      'city_catalog_selector_help':
          'Choose the city whose verified local guides you want to browse.',
      'city_catalog_status_available': 'available',
      'city_catalog_status_coming_soon': 'coming soon',
      'city_catalog_unavailable_title': 'City guides are not available yet',
      'city_catalog_unavailable_body':
          'We do not have verified local guides for {city} yet.',
      'city_catalog_request_cta': 'Request this city',
      'city_catalog_request_saved': 'City request saved.',
      'city_catalog_change_city': 'Change city',
      'city_catalog_select_warning':
          '{city} is not fully available yet. You can save it now, and local guides will appear when verified data is added.',
      'city_catalog_search_unavailable': 'No verified results for {city} yet.',
      'city_catalog_premium_unavailable':
          'Premium is active, but {city} guides are not available yet.',
      'estimated_expenses': 'Estimated expenses',
      'cost_dashboard_summary':
          'Track fees, refunds, installments, and disputed amounts.',
      'category_health_asl': 'Health / ASL',
      'category_housing_rent': 'Housing / Rent',
      'category_utilities': 'Bills & Utilities',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'Internet & Phone',
      'category_public_office': 'Comune / Registry',
      'category_work_inps': 'Work / INPS',
      'category_university': 'University / Student',
      'category_general': 'General',
      'category_general_help': 'General admin help',
      'trust_title': 'Trust',
      'problem_input_placeholder': 'Describe the problem in your own words.',
      'search_placeholder_generic': 'Search by title, tag, or description...',
      'problem_example_1': 'I want to remove Canone RAI from my bill',
      'problem_example_2': 'My gas bill is too high',
      'problem_example_3': 'I need to change my family doctor',
      'problem_example_4': 'I want to cancel internet',
      'problem_example_5': 'My landlord is not fixing the heating',
      'problem_example_6': 'I need NASpI',
      'all_label': 'All',
      'no_procedures_yet_title': 'No procedures yet',
      'no_procedures_yet_body':
          'This category does not have active procedures yet.',
      'onboarding_scope_title': 'What can UfficioFacile help with?',
      'onboarding_scope_body':
          'Bills, Canone RAI, health, rent, telecom, work, university, benefits, loans, refunds, and public-office tasks.',
      'privacy_body':
          'UfficioFacile helps you organize steps and write clearly. Always verify official rules, offices, deadlines, and eligibility before you send anything.',
      'optional_profile_setup': 'Optional profile setup',
      'full_name': 'Full name',
      'codice_fiscale': 'Codice fiscale',
      'city_label': 'City',
      'plan_title': 'Your plan',
      'plan_intro': 'Choose the level of help that fits your situation.',
      'plan_screenshot_limit_note':
          'Free accounts cannot take screenshots. Premium removes screenshot blocking on this device.',
      'current_plan_label': 'Current plan',
      'free_plan_label': 'Free',
      'plus_plan_label': 'Plus',
      'premium_plan_label': 'Premium',
      'catalog_load_error':
          'Catalog could not be loaded. Please update the app.',
      'retry': 'Retry',
      'not_found': 'We could not find that page.',
      'back_to_dashboard': 'Back to dashboard',
      'one_shot_consultancy_label': 'One-shot consultancy',
      'admin_grant_label': 'Admin grant',
      'free_plan_desc':
          'Public categories, intelligent search, and basic guidance with limits.',
      'plus_plan_desc':
          'More packs, more saved requests, larger dashboards, and priority requests.',
      'premium_plan_desc':
          'All premium guides, all money-saving categories, full vaults, advanced scanner, reminders, and private help.',
      'paywall_open_plan': 'See plans',
      'paywall_maybe_later': 'Maybe later',
      'payment_setup_message':
          'Purchase options appear when billing is configured for your workspace.',
      'sync_same_device_notice':
          'Sign in to sync your UfficioFacile data with the same verified device.',
      'already_unlocked': 'Already unlocked',
      'of_label': 'of',
      'packs_used_this_month': 'packs used this month',
      'startup_loading': 'Starting UfficioFacile...',
      'startup_continuing_local': 'Continuing in local mode.',
      'startup_diagnostics': 'Startup diagnostics',
      'startup_continue_local_mode': 'Continue in local mode',
      'startup_continue_local_only': 'Continue local-only',
      'startup_reset_data': 'Reset startup data',
      'startup_error_title': 'UfficioFacile could not finish startup.',
      'startup_unknown_error': 'Unknown startup error.',
      'forgot_password_title': 'Forgot password?',
      'forgot_password_intro':
          'Enter your email and we will send a reset link if the account exists.',
      'reset_password_title': 'Reset password',
      'reset_password_intro': 'Choose a new password for your account.',
      'reset_password_send_link': 'Send reset link',
      'reset_password_sent_generic':
          'If an account exists for this email, we sent a reset link.',
      'confirm_new_password': 'Confirm new password',
      'password_min_length': 'Choose a password with at least 8 characters.',
      'passwords_do_not_match': 'The passwords do not match.',
      'password_updated_success': 'Password updated successfully.',
      'update_password': 'Update password',
      'change_password_title': 'Change password',
      'change_password_intro': 'Update the password for this account.',
      'auth_confirm_email_message': 'Check your email to confirm your account.',
      'auth_email_confirmed_title': 'Email confirmed',
      'auth_email_confirmed_body':
          'Your account is confirmed. Go back to the app and log in there.',
      'auth_remember_me': 'Remember me',
      'auth_remember_me_hint':
          'Keep this email on this device and let Android offer to save your password.',
      'account_change_password': 'Change password',
      'paywall_premium_body':
          'This guide is part of UfficioFacile Premium. You can still browse free guides, or choose a plan to unlock deeper checklists, templates, and private support.',
      'paywall_section_locked_body':
          'This section is part of UfficioFacile Premium.',
      'paywall_usage_label': 'Usage',
      'request_consultancy': 'Request consultancy',
      'choose_plan': 'Choose plan',
    },
    'it': {
      'app_title': 'UfficioFacile',
      'hero_title':
          'Raccontaci il problema. Troviamo la procedura italiana giusta.',
      'hero_subtitle':
          'Usa parole normali: bollette, ASL, contratto di affitto, università, INPS, documenti. UfficioFacile collega il tuo problema alla categoria, ai passaggi, ai documenti e ai contatti giusti.',
      'start_problem': 'Parti dal mio problema',
      'browse_procedures': 'Esplora procedure',
      'utilities_bills': 'Bollette e utenze',
      'saved_requests': 'Richieste salvate',
      'what_help': 'Di cosa hai bisogno?',
      'onboarding_title': 'Burocrazia italiana, passo dopo passo.',
      'onboarding_subtitle':
          'Organizza procedure, promemoria, documenti e messaggi formali per bollette, affitto, sanità, università e uffici pubblici.',
      'onboarding_demo_title': 'UfficioFacile',
      'onboarding_demo_subtitle':
          'Gestisci la burocrazia italiana senza perderti.',
      'onboarding_card_1_title': 'Trova la procedura giusta',
      'onboarding_card_1_body':
          'Scegli una categoria e scopri cosa fare, dove andare e quali documenti servono.',
      'onboarding_card_2_title': 'Usa contatti verificati',
      'onboarding_card_2_body':
          'Trova link ufficiali, uffici, PEC, email e moduli quando sono disponibili.',
      'onboarding_card_3_title': 'Sblocca aiuto premium',
      'onboarding_card_3_body':
          'Risparmia tempo con guide più approfondite, richieste di nuovi problemi e supporto privato.',
      'privacy_title': 'Privacy e disclaimer',
      'skip': 'Salta',
      'next': 'Avanti',
      'done': 'Fine',
      'profile': 'Profilo',
      'profile_full_name': 'Nome completo',
      'profile_codice_fiscale': 'Codice fiscale',
      'profile_city': 'Città',
      'profile_language': 'Lingua',
      'profile_backend_mode': 'Modalità backend',
      'profile_backend_supabase': 'Sincronizzazione Supabase attiva',
      'profile_backend_local': 'Modalità solo locale',
      'profile_save': 'Salva profilo',
      'profile_saving': 'Salvataggio profilo...',
      'profile_saved': 'Profilo salvato',
      'profile_save_failed': 'Non siamo riusciti a salvare il profilo adesso.',
      'profile_sync_settings': 'Impostazioni di sincronizzazione',
      'help': 'Aiuto',
      'admin': 'Admin',
      'generate_pack': 'Genera pack',
      'save_request': 'Salva richiesta',
      'copied': 'Copiato',
      'request_saved': 'Richiesta salvata',
      'short_message': 'Messaggio breve',
      'email': 'Email',
      'pec': 'PEC / Formale',
      'follow_up': 'Sollecito',
      'strong_follow_up': 'Sollecito forte',
      'attachments': 'Allegati',
      'next_steps': 'Prossimi passi',
      'warnings': 'Avvisi',
      'disclaimer_short':
          'Supporto pratico per organizzazione e scrittura. Verifica sempre le istruzioni finali sul sito ufficiale o con l’ufficio competente.',
      'upcoming_reminders': 'Promemoria in arrivo',
      'requests_follow_up': 'Da sollecitare',
      'drafts': 'Bozze',
      'recent_requests': 'Richieste recenti',
      'problem_examples': 'Esempi',
      'recommendations': 'Percorsi consigliati',
      'no_results':
          'Non c’è ancora un risultato vicino. Puoi usare comunque la richiesta formale generica.',
      'compare_offers': 'Confronta offerte',
      'understand_bill': 'Capisci la bolletta',
      'canone_rai': 'Canone RAI',
      'telecom': 'Internet e telefono',
      'admin_panel': 'Pannello admin',
      'demo_data': 'Dati di esempio',
      'scan_situation': 'Analizza la mia situazione',
      'city_packs': 'City pack',
      'student_mode': 'Modalità studente',
      'tenant_mode': 'Modalità inquilino',
      'life_checklist': 'Checklist vita in Italia',
      'proof_folder': 'Cartella prove',
      'official_links': 'Link ufficiali',
      'cost_dashboard': 'Dashboard costi',
      'document_vault': 'Archivio documenti',
      'contacts_directory': 'Rubrica contatti',
      'calendar': 'Calendario',
      'plan': 'Piano',
      'free_plan': 'Gratis',
      'pro_plan': 'Premium',
      'consultant_plan': 'Consulenza',
      'beta_access_active': 'Accesso a pagamento attivo',
      'upgrade_to_pro': 'Passa a Premium',
      'premium_feature': 'Funzione Premium',
      'auth_account': 'Account',
      'auth_login': 'Accedi',
      'auth_create_account': 'Crea account',
      'auth_email': 'Email',
      'auth_password': 'Password',
      'auth_continue_public': 'Continua a consultare le guide pubbliche',
      'auth_login_subtitle':
          'Usa email e password per aprire il tuo spazio privato.',
      'auth_signup_subtitle':
          'Crea un account per salvare e sincronizzare richieste, promemoria e dettagli dei documenti.',
      'auth_login_or_signup': 'Accedi o crea un account',
      'auth_required_title': 'Account richiesto',
      'auth_required_message':
          'Crea un account per salvare e sincronizzare documenti, richieste e promemoria.',
      'auth_required_feature': 'Per aprire questa sezione ti serve un account.',
      'auth_wait': 'Attendi...',
      'auth_reset_password': 'Invia email per reimpostare la password',
      'auth_reset_sent':
          'Email per reimpostare la password inviata. Controlla la tua casella.',
      'auth_signup_success':
          'Account creato. Se la conferma email è attiva, conferma l’indirizzo prima di accedere.',
      'account_title': 'Il mio account',
      'account_email': 'Email',
      'account_not_signed_in': 'Non hai effettuato l’accesso',
      'account_plan': 'Piano',
      'account_log_out': 'Esci',
      'signed_out': 'Disconnessione effettuata',
      'account_privacy': 'Centro privacy',
      'account_delete': 'Elimina account',
      'access_denied_title': 'Accesso negato',
      'access_denied_message':
          'Il tuo account non ha accesso a questa sezione.',
      'admin_overview': 'Panoramica',
      'admin_users': 'Utenti',
      'admin_premium': 'Premium',
      'admin_catalog': 'Catalogo',
      'admin_problem_requests': 'Richieste problema',
      'admin_consultancy': 'Consulenze',
      'admin_content_manager': 'Gestione contenuti',
      'admin_security_checklist': 'Checklist sicurezza',
      'admin_supabase_configured': 'Supabase configurato',
      'admin_authenticated': 'Autenticato',
      'admin_rls_enabled':
          'Scritture admin protette da RLS abilitate tramite migrazione',
      'admin_anon_only': 'L’app client usa solo la chiave anon',
      'guided_selector': 'Selettore guidato',
      'open': 'Apri',
      'cta_problem_title': 'Non trovi il tuo problema?',
      'cta_problem_body':
          'Raccontaci di cosa hai bisogno. Lo controlleremo e lo aggiungeremo il prima possibile.',
      'cta_problem_button': 'Richiedi un nuovo problema',
      'cta_problem_thanks':
          'Grazie. Abbiamo ricevuto la tua richiesta e la controlleremo al più presto.',
      'cta_consultancy_title': 'Hai bisogno di aiuto privato?',
      'cta_consultancy_body':
          'I membri Premium possono richiedere assistenza privata via email. Gli utenti free possono richiederla con un pagamento extra quando disponibile.',
      'cta_consultancy_disclaimer':
          'UfficioFacile offre guida pratica, non consulenza legale, fiscale o medica. Verifica sempre le istruzioni finali sul sito ufficiale o con l’ufficio competente.',
      'cta_consultancy_request': 'Richiedi assistenza privata',
      'cta_consultancy_unlock': 'Sblocca assistenza privata',
      'cta_consultancy_upgrade': 'Passa a Premium',
      'cta_consultancy_email': 'Invia il caso via email',
      'cta_payment_unavailable':
          'I pagamenti Premium non sono ancora disponibili. Contatta il supporto.',
      'import_bundled_content': 'Importa i contenuti inclusi nel CMS',
      'premium_locked_title': 'Guida Premium',
      'unlock_this_guide_only': 'Sblocca solo questa guida',
      'single_unlock_available': 'Sblocco singolo disponibile',
      'payment_not_active_yet': 'Il pagamento non è ancora attivo.',
      'upgrade_to_premium': 'Passa a Premium',
      'my_italy_life': 'La mia vita in Italia',
      'checklist_progress': 'Avanzamento checklist',
      'deadlines_short': 'Scadenze',
      'city_pack_title': 'Pacchetto città',
      'city_catalog_label': 'Città del catalogo',
      'city_catalog_chip_prefix': 'Città',
      'city_catalog_selector': 'Città delle guide',
      'city_catalog_selector_help':
          'Scegli la città di cui vuoi consultare le guide locali verificate.',
      'city_catalog_status_available': 'disponibile',
      'city_catalog_status_coming_soon': 'in arrivo',
      'city_catalog_unavailable_title':
          'Le guide per questa città non sono ancora disponibili',
      'city_catalog_unavailable_body':
          'Non abbiamo ancora guide locali verificate per {city}.',
      'city_catalog_request_cta': 'Richiedi questa città',
      'city_catalog_request_saved': 'Richiesta città salvata.',
      'city_catalog_change_city': 'Cambia città',
      'city_catalog_select_warning':
          '{city} non è ancora disponibile in modo completo. Puoi salvarla ora e le guide locali appariranno quando aggiungeremo dati verificati.',
      'city_catalog_search_unavailable':
          'Non ci sono ancora risultati verificati per {city}.',
      'city_catalog_premium_unavailable':
          'Premium è attivo, ma le guide per {city} non sono ancora disponibili.',
      'estimated_expenses': 'Spese stimate',
      'cost_dashboard_summary':
          'Controlla costi, rimborsi, rate e importi contestati.',
      'category_health_asl': 'Salute / ASL',
      'category_housing_rent': 'Casa / Affitto',
      'category_utilities': 'Bollette e utenze',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'Internet e telefono',
      'category_public_office': 'Comune / Anagrafe',
      'category_work_inps': 'Lavoro / INPS',
      'category_university': 'Università / Studenti',
      'category_general': 'Generale',
      'category_general_help': 'Aiuto amministrativo generale',
      'trust_title': 'Affidabilità',
      'problem_input_placeholder': 'Descrivi il problema con parole tue.',
      'search_placeholder_generic': 'Cerca per titolo, tag o descrizione...',
      'problem_example_1': 'Voglio togliere il Canone RAI dalla bolletta',
      'problem_example_2': 'La bolletta del gas è troppo alta',
      'problem_example_3': 'Devo cambiare medico di base',
      'problem_example_4': 'Voglio disdire internet',
      'problem_example_5': 'Il proprietario non aggiusta il riscaldamento',
      'problem_example_6': 'Ho bisogno della NASpI',
      'all_label': 'Tutto',
      'no_procedures_yet_title': 'Nessuna procedura disponibile',
      'no_procedures_yet_body':
          'Questa categoria non ha ancora procedure attive.',
      'onboarding_scope_title': 'Con cosa può aiutarti UfficioFacile?',
      'onboarding_scope_body':
          'Bollette, Canone RAI, sanità, affitto, telecom, lavoro, università, bonus, prestiti, rimborsi e pratiche con uffici pubblici.',
      'privacy_body':
          'UfficioFacile ti aiuta a organizzare i passaggi e scrivere in modo chiaro. Verifica sempre regole ufficiali, uffici, scadenze e requisiti prima di inviare qualcosa.',
      'optional_profile_setup': 'Profilo facoltativo',
      'full_name': 'Nome completo',
      'codice_fiscale': 'Codice fiscale',
      'city_label': 'Città',
      'plan_title': 'Il tuo piano',
      'plan_intro':
          'Scegli il livello di aiuto più adatto alla tua situazione.',
      'plan_screenshot_limit_note':
          'Gli account gratuiti non possono fare screenshot. Premium rimuove il blocco screenshot su questo dispositivo.',
      'current_plan_label': 'Piano attuale',
      'free_plan_label': 'Free',
      'plus_plan_label': 'Plus',
      'premium_plan_label': 'Premium',
      'catalog_load_error':
          'Il catalogo non può essere caricato. Aggiorna l’app.',
      'retry': 'Riprova',
      'not_found': 'Non abbiamo trovato questa pagina.',
      'back_to_dashboard': 'Torna alla dashboard',
      'one_shot_consultancy_label': 'Consulenza una tantum',
      'admin_grant_label': 'Concessione admin',
      'free_plan_desc':
          'Categorie pubbliche, ricerca intelligente e guide di base con limiti.',
      'plus_plan_desc':
          'Più pack, più richieste salvate, dashboard più ampie e richieste prioritarie.',
      'premium_plan_desc':
          'Tutte le guide Premium, tutte le categorie che fanno risparmiare, archivi completi, scanner avanzato, promemoria e aiuto privato.',
      'paywall_open_plan': 'Apri i piani',
      'paywall_maybe_later': 'Forse più tardi',
      'payment_setup_message':
          'Le opzioni di acquisto compaiono quando la fatturazione è configurata per il tuo workspace.',
      'sync_same_device_notice':
          'Accedi per sincronizzare i dati di UfficioFacile con questo stesso dispositivo verificato.',
      'already_unlocked': 'Già sbloccato',
      'of_label': 'di',
      'packs_used_this_month': 'pack usati questo mese',
      'startup_loading': 'Avvio di UfficioFacile...',
      'startup_continuing_local': 'Continua in modalità locale.',
      'startup_diagnostics': 'Diagnostica avvio',
      'startup_continue_local_mode': 'Continua in modalità locale',
      'startup_continue_local_only': 'Continua solo locale',
      'startup_reset_data': 'Reimposta dati di avvio',
      'startup_error_title':
          'UfficioFacile non è riuscito a completare l’avvio.',
      'startup_unknown_error': 'Errore di avvio sconosciuto.',
      'forgot_password_title': 'Password dimenticata?',
      'forgot_password_intro':
          'Inserisci la tua email e invieremo un link di reset se l’account esiste.',
      'reset_password_title': 'Reimposta password',
      'reset_password_intro': 'Scegli una nuova password per il tuo account.',
      'reset_password_send_link': 'Invia link di reset',
      'reset_password_sent_generic':
          'Se esiste un account per questa email, abbiamo inviato un link di reset.',
      'confirm_new_password': 'Conferma nuova password',
      'password_min_length': 'Scegli una password di almeno 8 caratteri.',
      'passwords_do_not_match': 'Le password non coincidono.',
      'password_updated_success': 'Password aggiornata con successo.',
      'update_password': 'Aggiorna password',
      'change_password_title': 'Cambia password',
      'change_password_intro': 'Aggiorna la password di questo account.',
      'auth_confirm_email_message':
          'Controlla la tua email per confermare l’account.',
      'auth_email_confirmed_title': 'Email confermata',
      'auth_email_confirmed_body':
          'Il tuo account è confermato. Torna nell’app e accedi lì.',
      'auth_remember_me': 'Ricordami',
      'auth_remember_me_hint':
          'Tieni questa email su questo dispositivo e lascia che Android proponga di salvare la password.',
      'account_change_password': 'Cambia password',
      'paywall_premium_body':
          'Questa guida fa parte di UfficioFacile Premium. Puoi continuare a esplorare le guide gratuite oppure scegliere un piano per sbloccare checklist più approfondite, modelli e supporto privato.',
      'paywall_section_locked_body':
          'Questa sezione fa parte di UfficioFacile Premium.',
      'paywall_usage_label': 'Utilizzo',
      'request_consultancy': 'Richiedi consulenza',
      'choose_plan': 'Scegli piano',
    },
    'fa': {
      'app_title': 'UfficioFacile',
      'hero_title':
          'مشکل را بگو. ما روند اداری درست در ایتالیا را پیدا می‌کنیم.',
      'hero_subtitle':
          'با کلمات عادی بنویس: قبض، ASL، قرارداد اجاره، دانشگاه، INPS، مدارک. اوفیتسیو فاسیله مشکل تو را به دسته‌بندی، مراحل، مدارک و تماس‌های درست وصل می‌کند.',
      'start_problem': 'از مشکل من شروع کن',
      'browse_procedures': 'مرور فرایندها',
      'utilities_bills': 'قبض‌ها و خدمات',
      'saved_requests': 'درخواست‌های ذخیره‌شده',
      'what_help': 'در چه چیزی کمک می‌خواهید؟',
      'onboarding_title': 'کارهای اداری ایتالیا، مرحله به مرحله.',
      'onboarding_subtitle':
          'برای قبض، اجاره، درمان، دانشگاه و اداره‌های عمومی، فرایندها، یادآورها، مدارک و پیام‌های رسمی را مدیریت کنید.',
      'onboarding_demo_title': 'UfficioFacile',
      'onboarding_demo_subtitle':
          'کارهای اداری ایتالیا را بدون سردرگمی انجام بده.',
      'onboarding_card_1_title': 'روند درست را پیدا کن',
      'onboarding_card_1_body':
          'یک دسته را انتخاب کن تا ببینی چه کاری باید انجام بدهی، کجا بروی و چه مدارکی لازم است.',
      'onboarding_card_2_title': 'از راه‌های تماس معتبر استفاده کن',
      'onboarding_card_2_body':
          'در صورت وجود، لینک‌های رسمی، اداره‌ها، آدرس PEC، ایمیل‌ها و فرم‌ها را ببین.',
      'onboarding_card_3_title': 'کمک پریمیوم را باز کن',
      'onboarding_card_3_body':
          'با راهنماهای عمیق‌تر، درخواست برای مشکلات جدید و پشتیبانی خصوصی در زمان صرفه‌جویی کن.',
      'privacy_title': 'حریم خصوصی و توضیحات',
      'skip': 'رد کردن',
      'next': 'بعدی',
      'done': 'تمام',
      'profile': 'پروفایل',
      'profile_full_name': 'نام کامل',
      'profile_codice_fiscale': 'کد مالیاتی',
      'profile_city': 'شهر',
      'profile_language': 'زبان',
      'profile_backend_mode': 'حالت backend',
      'profile_backend_supabase': 'همگام‌سازی Supabase فعال است',
      'profile_backend_local': 'حالت فقط محلی',
      'profile_save': 'ذخیره پروفایل',
      'profile_saving': 'در حال ذخیره پروفایل...',
      'profile_saved': 'پروفایل ذخیره شد',
      'profile_save_failed': 'الان نتوانستیم پروفایل را ذخیره کنیم.',
      'profile_sync_settings': 'تنظیمات همگام‌سازی',
      'help': 'راهنما',
      'admin': 'مدیر',
      'generate_pack': 'ساخت بسته',
      'save_request': 'ذخیره درخواست',
      'copied': 'کپی شد',
      'request_saved': 'درخواست ذخیره شد',
      'short_message': 'پیام کوتاه',
      'email': 'ایمیل',
      'pec': 'PEC / رسمی',
      'follow_up': 'پیگیری',
      'strong_follow_up': 'پیگیری جدی‌تر',
      'attachments': 'پیوست‌ها',
      'next_steps': 'قدم‌های بعدی',
      'warnings': 'هشدارها',
      'disclaimer_short':
          'فقط پشتیبانی عملی برای نوشتن و سازمان‌دهی. همیشه دستور نهایی را در سایت رسمی یا با اداره مربوط بررسی کنید.',
      'upcoming_reminders': 'یادآورهای پیش رو',
      'requests_follow_up': 'نیازمند پیگیری',
      'drafts': 'پیش‌نویس‌ها',
      'recent_requests': 'درخواست‌های اخیر',
      'problem_examples': 'نمونه‌ها',
      'recommendations': 'مسیرهای پیشنهادی',
      'no_results':
          'هنوز نتیجه نزدیک پیدا نشد. می‌توانید از درخواست رسمی عمومی استفاده کنید.',
      'compare_offers': 'مقایسه پیشنهادها',
      'understand_bill': 'قبض من را توضیح بده',
      'canone_rai': 'Canone RAI',
      'telecom': 'اینترنت و تلفن',
      'admin_panel': 'پنل مدیریت',
      'demo_data': 'داده نمونه',
      'scan_situation': 'وضعیت من را بررسی کن',
      'city_packs': 'بسته‌های شهری',
      'student_mode': 'حالت دانشجویی',
      'tenant_mode': 'حالت مستأجر',
      'life_checklist': 'چک‌لیست زندگی در ایتالیا',
      'proof_folder': 'پوشه مدارک',
      'official_links': 'لینک‌های رسمی',
      'cost_dashboard': 'داشبورد هزینه‌ها',
      'document_vault': 'آرشیو مدارک',
      'contacts_directory': 'دفترچه مخاطبان',
      'calendar': 'تقویم',
      'plan': 'پلن',
      'free_plan': 'رایگان',
      'pro_plan': 'پریمیوم',
      'consultant_plan': 'مشاوره',
      'beta_access_active': 'دسترسی پولی فعال است',
      'upgrade_to_pro': 'ارتقا به پریمیوم',
      'premium_feature': 'ویژگی پریمیوم',
      'auth_account': 'حساب کاربری',
      'auth_login': 'ورود',
      'auth_create_account': 'ساخت حساب',
      'auth_email': 'ایمیل',
      'auth_password': 'رمز عبور',
      'auth_continue_public': 'ادامه مرور راهنماهای عمومی',
      'auth_login_subtitle': 'با ایمیل و رمز عبور وارد فضای خصوصی خود شوید.',
      'auth_signup_subtitle':
          'برای ذخیره و همگام‌سازی درخواست‌ها، یادآورها و جزئیات مدارک حساب بسازید.',
      'auth_login_or_signup': 'ورود یا ساخت حساب',
      'auth_required_title': 'حساب لازم است',
      'auth_required_message':
          'برای ذخیره و همگام‌سازی مدارک، درخواست‌ها و یادآورها حساب بسازید.',
      'auth_required_feature': 'برای باز کردن این بخش به حساب نیاز دارید.',
      'auth_wait': 'لطفاً صبر کنید...',
      'auth_reset_password': 'ایمیل بازنشانی رمز عبور را ارسال کن',
      'auth_reset_sent':
          'ایمیل بازنشانی رمز عبور ارسال شد. صندوق ورودی را بررسی کنید.',
      'auth_signup_success':
          'حساب ساخته شد. اگر تأیید ایمیل فعال باشد، قبل از ورود ایمیل خود را تأیید کنید.',
      'account_title': 'حساب من',
      'account_email': 'ایمیل',
      'account_not_signed_in': 'وارد نشده‌اید',
      'account_plan': 'پلن',
      'account_log_out': 'خروج',
      'account_privacy': 'مرکز حریم خصوصی',
      'account_delete': 'حذف حساب',
      'access_denied_title': 'دسترسی مجاز نیست',
      'access_denied_message': 'حساب شما به این بخش دسترسی ندارد.',
      'admin_overview': 'نمای کلی',
      'admin_users': 'کاربران',
      'admin_premium': 'پریمیوم',
      'admin_catalog': 'کاتالوگ',
      'admin_problem_requests': 'درخواست‌های مشکل',
      'admin_consultancy': 'مشاوره',
      'admin_content_manager': 'مدیریت محتوا',
      'admin_security_checklist': 'چک‌لیست امنیت',
      'admin_supabase_configured': 'Supabase پیکربندی شده است',
      'admin_authenticated': 'احراز هویت شده',
      'admin_rls_enabled': 'نوشتن‌های مدیریتی با RLS محافظت می‌شوند',
      'admin_anon_only': 'برنامه فقط از کلید anon در سمت کاربر استفاده می‌کند',
      'guided_selector': 'انتخاب‌گر مرحله‌ای',
      'open': 'باز کردن',
      'cta_problem_title': 'مشکل شما اینجا نیست؟',
      'cta_problem_body':
          'آنچه نیاز دارید را برای ما بفرستید. بررسی می‌کنیم و هرچه سریع‌تر اضافه می‌کنیم.',
      'cta_problem_button': 'ثبت مشکل جدید',
      'cta_problem_thanks':
          'ممنون. درخواست شما دریافت شد و خیلی زود بررسی می‌شود.',
      'cta_consultancy_title': 'به کمک خصوصی نیاز دارید؟',
      'cta_consultancy_body':
          'اعضای پریمیوم می‌توانند راهنمایی خصوصی ایمیلی بگیرند. کاربران رایگان در صورت فعال بودن پرداخت اضافه می‌توانند درخواست بدهند.',
      'cta_consultancy_disclaimer':
          'UfficioFacile راهنمای عملی ارائه می‌دهد، نه مشاوره حقوقی، مالیاتی یا پزشکی. همیشه دستور نهایی را در سایت رسمی یا با اداره مربوط بررسی کنید.',
      'cta_consultancy_request': 'درخواست راهنمایی خصوصی',
      'cta_consultancy_unlock': 'فعال‌سازی راهنمایی خصوصی',
      'cta_consultancy_upgrade': 'ارتقا به پریمیوم',
      'cta_consultancy_email': 'ارسال پرونده با ایمیل',
      'cta_payment_unavailable':
          'پرداخت‌های پریمیوم هنوز فعال نیستند. با پشتیبانی تماس بگیرید.',
      'import_bundled_content': 'وارد کردن محتوای پیش‌فرض به CMS',
      'premium_locked_title': 'راهنمای پریمیوم',
      'unlock_this_guide_only': 'فقط همین راهنما را باز کن',
      'single_unlock_available': 'باز کردن تکی موجود است',
      'payment_not_active_yet': 'پرداخت هنوز فعال نیست.',
      'upgrade_to_premium': 'ارتقا به پریمیوم',
      'my_italy_life': 'زندگی من در ایتالیا',
      'checklist_progress': 'پیشرفت چک‌لیست',
      'deadlines_short': 'مهلت‌ها',
      'city_pack_title': 'بسته شهر',
      'city_catalog_label': 'شهر کاتالوگ',
      'city_catalog_chip_prefix': 'شهر',
      'city_catalog_selector': 'شهر راهنماها',
      'city_catalog_selector_help':
          'شهری را انتخاب کنید که می‌خواهید راهنماهای محلی تاییدشده آن را ببینید.',
      'city_catalog_status_available': 'موجود',
      'city_catalog_status_coming_soon': 'به‌زودی',
      'city_catalog_unavailable_title': 'راهنماهای این شهر هنوز آماده نیست',
      'city_catalog_unavailable_body':
          'هنوز راهنمای محلی تاییدشده‌ای برای {city} نداریم.',
      'city_catalog_request_cta': 'درخواست این شهر',
      'city_catalog_request_saved': 'درخواست شهر ذخیره شد.',
      'city_catalog_change_city': 'تغییر شهر',
      'city_catalog_select_warning':
          '{city} هنوز کامل در دسترس نیست. می‌توانید آن را ذخیره کنید و وقتی داده تاییدشده اضافه شد راهنماها نمایش داده می‌شوند.',
      'city_catalog_search_unavailable':
          'هنوز نتیجه تاییدشده‌ای برای {city} نداریم.',
      'city_catalog_premium_unavailable':
          'پریمیوم فعال است، اما راهنماهای {city} هنوز در دسترس نیستند.',
      'estimated_expenses': 'هزینه‌های تخمینی',
      'cost_dashboard_summary':
          'کارمزدها، بازپرداخت‌ها، قسط‌ها و مبالغ مورد اختلاف را پیگیری کن.',
      'category_health_asl': 'سلامت / ASL',
      'category_housing_rent': 'خانه / اجاره',
      'category_utilities': 'قبض‌ها و خدمات',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'اینترنت و تلفن',
      'category_public_office': 'Comune / ثبت احوال',
      'category_work_inps': 'کار / INPS',
      'category_university': 'دانشگاه / دانشجو',
      'category_general': 'عمومی',
      'category_general_help': 'راهنمای اداری عمومی',
      'trust_title': 'اعتماد',
      'problem_input_placeholder': 'مشکل را با زبان خودت توضیح بده.',
      'search_placeholder_generic': 'بر اساس عنوان، برچسب یا توضیح جستجو کن...',
      'problem_example_1': 'می‌خواهم Canone RAI را از قبض حذف کنم',
      'problem_example_2': 'قبض گاز خیلی زیاد است',
      'problem_example_3': 'باید پزشک خانواده را عوض کنم',
      'problem_example_4': 'می‌خواهم اینترنت را لغو کنم',
      'problem_example_5': 'صاحبخانه گرمایش را تعمیر نمی‌کند',
      'problem_example_6': 'به NASpI نیاز دارم',
      'all_label': 'همه',
      'no_procedures_yet_title': 'هنوز فرایندی نیست',
      'no_procedures_yet_body': 'هنوز هیچ فرایند فعالی در این دسته وجود ندارد.',
      'onboarding_scope_title': 'UfficioFacile در چه چیزهایی کمک می‌کند؟',
      'onboarding_scope_body':
          'قبض‌ها، Canone RAI، درمان، اجاره، مخابرات، کار، دانشگاه، بونوس‌ها، وام‌ها، بازپرداخت‌ها و کارهای اداری با اداره‌های عمومی.',
      'privacy_body':
          'UfficioFacile به تو کمک می‌کند مراحل را مرتب کنی و واضح بنویسی. قبل از ارسال هر چیزی، همیشه قوانین رسمی، اداره مربوط، مهلت‌ها و شرایط را بررسی کن.',
      'optional_profile_setup': 'تنظیم اختیاری پروفایل',
      'full_name': 'نام کامل',
      'codice_fiscale': 'Codice fiscale',
      'city_label': 'شهر',
      'plan_title': 'پلن شما',
      'plan_intro': 'سطح کمکی را انتخاب کن که با وضعیت تو هماهنگ باشد.',
      'plan_screenshot_limit_note':
          'حساب‌های رایگان نمی‌توانند اسکرین‌شات بگیرند. پریمیوم محدودیت اسکرین‌شات را روی این دستگاه برمی‌دارد.',
      'current_plan_label': 'پلن فعلی',
      'free_plan_label': 'رایگان',
      'plus_plan_label': 'پلاس',
      'premium_plan_label': 'پریمیوم',
      'catalog_load_error':
          'کاتالوگ بارگذاری نشد. لطفاً برنامه را به‌روزرسانی کن.',
      'retry': 'تلاش دوباره',
      'signed_out': 'از حساب خارج شدی',
      'not_found': 'این صفحه پیدا نشد.',
      'back_to_dashboard': 'بازگشت به داشبورد',
      'one_shot_consultancy_label': 'مشاوره یک‌باره',
      'admin_grant_label': 'امتیاز مدیریتی',
      'free_plan_desc':
          'دسته‌های عمومی، جستجوی هوشمند و راهنمای پایه با محدودیت.',
      'plus_plan_desc':
          'بسته‌های بیشتر، درخواست‌های ذخیره‌شده بیشتر، داشبوردهای بزرگ‌تر و درخواست‌های اولویت‌دار.',
      'premium_plan_desc':
          'همه راهنماهای پریمیوم، همه دسته‌های صرفه‌جویی مالی، آرشیو کامل، اسکن پیشرفته، یادآورها و کمک خصوصی.',
      'paywall_open_plan': 'دیدن پلن‌ها',
      'paywall_maybe_later': 'بعداً',
      'payment_setup_message':
          'وقتی پرداخت برای این محیط فعال شود، گزینه‌های خرید اینجا نمایش داده می‌شوند.',
      'sync_same_device_notice':
          'برای همگام‌سازی داده‌های UfficioFacile با همین دستگاه تأییدشده وارد شوید.',
      'already_unlocked': 'قبلاً باز شده',
      'of_label': 'از',
      'packs_used_this_month': 'بسته استفاده شده در این ماه',
      'startup_loading': 'در حال شروع UfficioFacile...',
      'startup_continuing_local': 'ادامه در حالت محلی.',
      'startup_diagnostics': 'اطلاعات شروع',
      'startup_continue_local_mode': 'ادامه در حالت محلی',
      'startup_continue_local_only': 'ادامه فقط محلی',
      'startup_reset_data': 'بازنشانی داده‌های شروع',
      'startup_error_title': 'UfficioFacile نتوانست شروع را کامل کند.',
      'startup_unknown_error': 'خطای ناشناخته در شروع.',
      'forgot_password_title': 'رمز عبور را فراموش کرده‌اید؟',
      'forgot_password_intro':
          'ایمیل خود را وارد کنید تا اگر حساب وجود دارد، لینک بازنشانی برای شما ارسال شود.',
      'auth_email_confirmed_title': 'ایمیل تأیید شد',
      'auth_email_confirmed_body':
          'حساب شما تأیید شد. دوباره وارد شوید تا ادامه دهید.',
      'auth_remember_me': 'مرا به خاطر بسپار',
      'auth_remember_me_hint':
          'ایمیل شما را روی این دستگاه نگه می‌داریم تا ورود بعدی سریع‌تر شود.',
      'reset_password_title': 'بازنشانی رمز عبور',
      'reset_password_intro': 'یک رمز عبور جدید برای حساب خود انتخاب کنید.',
      'reset_password_send_link': 'ارسال لینک بازنشانی',
      'reset_password_sent_generic':
          'اگر برای این ایمیل حسابی وجود داشته باشد، لینک بازنشانی ارسال شد.',
      'confirm_new_password': 'تأیید رمز عبور جدید',
      'password_min_length': 'رمز عبوری با حداقل ۸ کاراکتر انتخاب کنید.',
      'passwords_do_not_match': 'رمزهای عبور با هم مطابقت ندارند.',
      'password_updated_success': 'رمز عبور با موفقیت به‌روزرسانی شد.',
      'update_password': 'به‌روزرسانی رمز عبور',
      'change_password_title': 'تغییر رمز عبور',
      'change_password_intro': 'رمز عبور این حساب را به‌روزرسانی کنید.',
      'auth_confirm_email_message': 'ایمیل خود را برای تأیید حساب بررسی کنید.',
      'account_change_password': 'تغییر رمز عبور',
      'paywall_premium_body':
          'این راهنما بخشی از UfficioFacile Premium است. هنوز می‌توانید راهنماهای رایگان را ببینید یا برای باز کردن چک‌لیست‌های عمیق‌تر، قالب‌ها و پشتیبانی خصوصی یک پلن انتخاب کنید.',
      'paywall_section_locked_body':
          'این بخش بخشی از UfficioFacile Premium است.',
      'paywall_usage_label': 'میزان استفاده',
      'request_consultancy': 'درخواست مشاوره',
      'choose_plan': 'انتخاب پلن',
    },
    'fr': {
      'app_title': 'UfficioFacile',
      'hero_title':
          'Dites-nous le problème. Nous trouvons la bonne démarche italienne.',
      'hero_subtitle':
          'Utilisez des mots simples : factures, ASL, bail, université, INPS, documents. UfficioFacile relie votre besoin à la bonne catégorie, aux étapes, aux documents et aux contacts utiles.',
      'start_problem': 'Partir de mon problème',
      'browse_procedures': 'Parcourir les démarches',
      'utilities_bills': 'Factures et contrats',
      'saved_requests': 'Demandes enregistrées',
      'what_help': 'De quoi avez-vous besoin ?',
      'onboarding_title': 'Les démarches italiennes, étape par étape.',
      'onboarding_subtitle':
          'Organisez vos démarches, rappels, documents et messages formels pour les factures, le logement, la santé, l’université et les bureaux publics.',
      'onboarding_demo_title': 'UfficioFacile',
      'onboarding_demo_subtitle':
          'Gérez les démarches italiennes sans vous perdre.',
      'onboarding_card_1_title': 'Trouver la bonne procédure',
      'onboarding_card_1_body':
          'Choisissez une catégorie et voyez quoi faire, où aller et quels documents préparer.',
      'onboarding_card_2_title': 'Utiliser des contacts vérifiés',
      'onboarding_card_2_body':
          'Retrouvez des liens officiels, bureaux, adresses PEC, emails et formulaires quand ils existent.',
      'onboarding_card_3_title': 'Débloquer l’aide Premium',
      'onboarding_card_3_body':
          'Gagnez du temps avec des guides plus complets, des demandes de nouveaux problèmes et un support privé.',
      'privacy_title': 'Confidentialité et avertissement',
      'skip': 'Passer',
      'next': 'Suivant',
      'done': 'Terminé',
      'profile': 'Profil',
      'profile_full_name': 'Nom complet',
      'profile_codice_fiscale': 'Code fiscal',
      'profile_city': 'Ville',
      'profile_language': 'Langue',
      'profile_backend_mode': 'Mode backend',
      'profile_backend_supabase': 'Synchronisation Supabase active',
      'profile_backend_local': 'Mode local uniquement',
      'profile_save': 'Enregistrer le profil',
      'profile_saving': 'Enregistrement du profil...',
      'profile_saved': 'Profil enregistré',
      'profile_save_failed':
          'Nous n’avons pas pu enregistrer le profil pour le moment.',
      'profile_sync_settings': 'Paramètres de synchronisation',
      'help': 'Aide',
      'admin': 'Admin',
      'generate_pack': 'Générer le pack',
      'save_request': 'Enregistrer la demande',
      'copied': 'Copié',
      'request_saved': 'Demande enregistrée',
      'short_message': 'Message court',
      'email': 'Email',
      'pec': 'PEC / Formel',
      'follow_up': 'Relance',
      'strong_follow_up': 'Relance formelle',
      'attachments': 'Pièces jointes',
      'next_steps': 'Prochaines étapes',
      'warnings': 'Points d’attention',
      'disclaimer_short':
          'Aide pratique à la rédaction et à l’organisation uniquement. Vérifiez toujours les instructions finales sur le site officiel ou auprès du bureau compétent.',
      'upcoming_reminders': 'Rappels à venir',
      'requests_follow_up': 'À relancer',
      'drafts': 'Brouillons',
      'recent_requests': 'Demandes récentes',
      'problem_examples': 'Exemples',
      'recommendations': 'Parcours recommandés',
      'no_results':
          'Aucun résultat proche pour le moment. Vous pouvez quand même utiliser la demande formelle générale.',
      'compare_offers': 'Comparer les offres',
      'understand_bill': 'Comprendre ma facture',
      'canone_rai': 'Canone RAI',
      'telecom': 'Internet et téléphone',
      'admin_panel': 'Panneau admin',
      'demo_data': 'Données d’exemple',
      'scan_situation': 'Analyser ma situation',
      'city_packs': 'Packs ville',
      'student_mode': 'Mode étudiant',
      'tenant_mode': 'Mode locataire',
      'life_checklist': 'Ma checklist Italie',
      'proof_folder': 'Dossier de preuves',
      'official_links': 'Liens officiels',
      'cost_dashboard': 'Tableau des coûts',
      'document_vault': 'Coffre de documents',
      'contacts_directory': 'Répertoire de contacts',
      'calendar': 'Calendrier',
      'plan': 'Offre',
      'free_plan': 'Gratuit',
      'pro_plan': 'Premium',
      'consultant_plan': 'Consultation',
      'beta_access_active': 'Accès payant actif',
      'upgrade_to_pro': 'Passer à Premium',
      'premium_feature': 'Fonction Premium',
      'auth_account': 'Compte',
      'auth_login': 'Se connecter',
      'auth_create_account': 'Créer un compte',
      'auth_email': 'Email',
      'auth_password': 'Mot de passe',
      'auth_continue_public': 'Continuer à parcourir les guides publics',
      'auth_login_subtitle':
          'Utilisez votre email et votre mot de passe pour ouvrir votre espace privé.',
      'auth_signup_subtitle':
          'Créez un compte pour enregistrer et synchroniser vos demandes, rappels et détails de documents.',
      'auth_login_or_signup': 'Se connecter ou créer un compte',
      'auth_required_title': 'Compte requis',
      'auth_required_message':
          'Créez un compte pour enregistrer et synchroniser vos documents, demandes et rappels.',
      'auth_required_feature':
          'Vous avez besoin d’un compte pour ouvrir cette section.',
      'auth_wait': 'Veuillez patienter...',
      'auth_reset_password': 'Envoyer un email de réinitialisation',
      'auth_reset_sent':
          'Email de réinitialisation envoyé. Vérifiez votre boîte de réception.',
      'auth_signup_success':
          'Compte créé. Si la confirmation par email est active, confirmez votre adresse avant de vous connecter.',
      'account_title': 'Mon compte',
      'account_email': 'Email',
      'account_not_signed_in': 'Non connecté',
      'account_plan': 'Offre',
      'account_log_out': 'Se déconnecter',
      'signed_out': 'Déconnexion effectuée',
      'account_privacy': 'Centre de confidentialité',
      'account_delete': 'Supprimer le compte',
      'access_denied_title': 'Accès refusé',
      'access_denied_message': 'Votre compte n’a pas accès à cette section.',
      'admin_overview': 'Vue d’ensemble',
      'admin_users': 'Utilisateurs',
      'admin_premium': 'Premium',
      'admin_catalog': 'Catalogue',
      'admin_problem_requests': 'Demandes de problème',
      'admin_consultancy': 'Consultations',
      'admin_content_manager': 'Gestionnaire de contenu',
      'admin_security_checklist': 'Checklist sécurité',
      'admin_supabase_configured': 'Supabase configuré',
      'admin_authenticated': 'Authentifié',
      'admin_rls_enabled': 'Écritures admin protégées par RLS via migration',
      'admin_anon_only': 'L’application cliente utilise uniquement la clé anon',
      'guided_selector': 'Sélecteur guidé',
      'open': 'Ouvrir',
      'cta_problem_title': 'Vous ne trouvez pas votre problème ?',
      'cta_problem_body':
          'Dites-nous ce dont vous avez besoin. Nous le vérifierons et l’ajouterons aussi vite que possible.',
      'cta_problem_button': 'Demander un nouveau problème',
      'cta_problem_thanks':
          'Merci. Nous avons reçu votre demande et nous allons l’examiner rapidement.',
      'cta_consultancy_title': 'Besoin d’une aide privée ?',
      'cta_consultancy_body':
          'Les membres Premium peuvent demander une aide privée par email. Les utilisateurs gratuits peuvent la demander avec un paiement supplémentaire quand il est disponible.',
      'cta_consultancy_disclaimer':
          'UfficioFacile fournit une aide pratique, pas un conseil juridique, fiscal ou médical. Vérifiez toujours les instructions finales sur le site officiel ou auprès du bureau compétent.',
      'cta_consultancy_request': 'Demander une aide privée',
      'cta_consultancy_unlock': 'Débloquer l’aide privée',
      'cta_consultancy_upgrade': 'Passer à Premium',
      'cta_consultancy_email': 'Envoyer mon dossier par email',
      'cta_payment_unavailable':
          'Les paiements Premium ne sont pas encore disponibles. Contactez le support.',
      'import_bundled_content': 'Importer le contenu intégré dans le CMS',
      'premium_locked_title': 'Guide Premium',
      'unlock_this_guide_only': 'Débloquer ce guide seulement',
      'single_unlock_available': 'Déblocage unique disponible',
      'payment_not_active_yet': 'Le paiement n’est pas encore actif.',
      'upgrade_to_premium': 'Passer à Premium',
      'my_italy_life': 'Ma vie en Italie',
      'checklist_progress': 'Progression de la checklist',
      'deadlines_short': 'Délais',
      'city_pack_title': 'Pack ville',
      'city_catalog_label': 'Ville du catalogue',
      'city_catalog_chip_prefix': 'Ville',
      'city_catalog_selector': 'Ville des guides',
      'city_catalog_selector_help':
          'Choisissez la ville dont vous voulez consulter les guides locaux vérifiés.',
      'city_catalog_status_available': 'disponible',
      'city_catalog_status_coming_soon': 'bientôt disponible',
      'city_catalog_unavailable_title':
          'Les guides pour cette ville ne sont pas encore disponibles',
      'city_catalog_unavailable_body':
          'Nous n’avons pas encore de guides locaux vérifiés pour {city}.',
      'city_catalog_request_cta': 'Demander cette ville',
      'city_catalog_request_saved': 'Demande de ville enregistrée.',
      'city_catalog_change_city': 'Changer de ville',
      'city_catalog_select_warning':
          '{city} n’est pas encore entièrement disponible. Vous pouvez l’enregistrer maintenant et les guides locaux apparaîtront quand des données vérifiées seront ajoutées.',
      'city_catalog_search_unavailable':
          'Aucun résultat vérifié pour {city} pour le moment.',
      'city_catalog_premium_unavailable':
          'Premium est actif, mais les guides pour {city} ne sont pas encore disponibles.',
      'estimated_expenses': 'Dépenses estimées',
      'cost_dashboard_summary':
          'Suivez les frais, remboursements, mensualités et montants contestés.',
      'category_health_asl': 'Santé / ASL',
      'category_housing_rent': 'Logement / Loyer',
      'category_utilities': 'Factures et contrats',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'Internet et téléphone',
      'category_public_office': 'Commune / Registre',
      'category_work_inps': 'Travail / INPS',
      'category_university': 'Université / Étudiant',
      'category_general': 'Général',
      'category_general_help': 'Aide administrative générale',
      'trust_title': 'Confiance',
      'problem_input_placeholder':
          'Décrivez le problème avec vos propres mots.',
      'search_placeholder_generic': 'Chercher par titre, tag ou description...',
      'problem_example_1': 'Je veux retirer le Canone RAI de ma facture',
      'problem_example_2': 'Ma facture de gaz est trop élevée',
      'problem_example_3': 'Je dois changer de médecin traitant',
      'problem_example_4': 'Je veux résilier internet',
      'problem_example_5': 'Mon propriétaire ne répare pas le chauffage',
      'problem_example_6': 'J’ai besoin de la NASpI',
      'all_label': 'Tout',
      'no_procedures_yet_title': 'Aucune démarche pour le moment',
      'no_procedures_yet_body':
          'Cette catégorie ne contient pas encore de démarches actives.',
      'onboarding_scope_title': 'Avec quoi UfficioFacile peut vous aider ?',
      'onboarding_scope_body':
          'Factures, Canone RAI, santé, logement, télécoms, travail, université, aides, prêts, remboursements et démarches auprès des bureaux publics.',
      'privacy_body':
          'UfficioFacile vous aide à organiser les étapes et à écrire clairement. Vérifiez toujours les règles officielles, les bureaux, les délais et les conditions avant tout envoi.',
      'optional_profile_setup': 'Profil facultatif',
      'full_name': 'Nom complet',
      'codice_fiscale': 'Codice fiscale',
      'city_label': 'Ville',
      'plan_title': 'Votre offre',
      'plan_intro':
          'Choisissez le niveau d’aide qui convient à votre situation.',
      'plan_screenshot_limit_note':
          'Les comptes gratuits ne peuvent pas faire de captures d’écran. Premium retire ce blocage sur cet appareil.',
      'current_plan_label': 'Offre actuelle',
      'free_plan_label': 'Gratuit',
      'plus_plan_label': 'Plus',
      'premium_plan_label': 'Premium',
      'catalog_load_error':
          'Le catalogue ne peut pas être chargé. Veuillez mettre l’application à jour.',
      'retry': 'Réessayer',
      'not_found': 'Cette page est introuvable.',
      'back_to_dashboard': 'Retour au tableau de bord',
      'one_shot_consultancy_label': 'Consultation ponctuelle',
      'admin_grant_label': 'Attribution admin',
      'free_plan_desc':
          'Catégories publiques, recherche intelligente et guides de base avec limites.',
      'plus_plan_desc':
          'Plus de packs, plus de demandes enregistrées, tableaux élargis et demandes prioritaires.',
      'premium_plan_desc':
          'Tous les guides Premium, toutes les catégories qui font économiser, coffres complets, scanner avancé, rappels et aide privée.',
      'paywall_open_plan': 'Voir les offres',
      'paywall_maybe_later': 'Plus tard',
      'payment_setup_message':
          'Les options d’achat apparaissent quand la facturation est configurée pour votre espace.',
      'sync_same_device_notice':
          'Connectez-vous pour synchroniser vos données UfficioFacile avec ce même appareil vérifié.',
      'already_unlocked': 'Déjà débloqué',
      'of_label': 'sur',
      'packs_used_this_month': 'packs utilisés ce mois-ci',
      'startup_loading': 'Démarrage de UfficioFacile...',
      'startup_continuing_local': 'Continuation en mode local.',
      'startup_diagnostics': 'Diagnostic de démarrage',
      'startup_continue_local_mode': 'Continuer en mode local',
      'startup_continue_local_only': 'Continuer en local uniquement',
      'startup_reset_data': 'Réinitialiser les données de démarrage',
      'startup_error_title': 'UfficioFacile n’a pas pu terminer le démarrage.',
      'startup_unknown_error': 'Erreur de démarrage inconnue.',
      'forgot_password_title': 'Mot de passe oublié ?',
      'forgot_password_intro':
          'Entrez votre email et nous enverrons un lien de réinitialisation si le compte existe.',
      'auth_email_confirmed_title': 'Email confirmé',
      'auth_email_confirmed_body':
          'Votre compte est confirmé. Connectez-vous de nouveau pour continuer.',
      'auth_remember_me': 'Se souvenir de moi',
      'auth_remember_me_hint':
          'Conserver votre email sur cet appareil pour accélérer la prochaine connexion.',
      'reset_password_title': 'Réinitialiser le mot de passe',
      'reset_password_intro':
          'Choisissez un nouveau mot de passe pour votre compte.',
      'reset_password_send_link': 'Envoyer le lien de réinitialisation',
      'reset_password_sent_generic':
          'Si un compte existe pour cet email, nous avons envoyé un lien de réinitialisation.',
      'confirm_new_password': 'Confirmer le nouveau mot de passe',
      'password_min_length':
          'Choisissez un mot de passe d’au moins 8 caractères.',
      'passwords_do_not_match': 'Les mots de passe ne correspondent pas.',
      'password_updated_success': 'Mot de passe mis à jour avec succès.',
      'update_password': 'Mettre à jour le mot de passe',
      'change_password_title': 'Changer le mot de passe',
      'change_password_intro': 'Mettez à jour le mot de passe de ce compte.',
      'auth_confirm_email_message':
          'Vérifiez votre email pour confirmer votre compte.',
      'account_change_password': 'Changer le mot de passe',
      'paywall_premium_body':
          'Ce guide fait partie de UfficioFacile Premium. Vous pouvez continuer à parcourir les guides gratuits ou choisir une offre pour débloquer des checklists plus détaillées, des modèles et une aide privée.',
      'paywall_section_locked_body':
          'Cette section fait partie de UfficioFacile Premium.',
      'paywall_usage_label': 'Utilisation',
      'request_consultancy': 'Demander une consultation',
      'choose_plan': 'Choisir cette offre',
    },
    'es': {
      'app_title': 'UfficioFacile',
      'hero_title':
          'Cuéntanos el problema. Encontramos el trámite italiano correcto.',
      'hero_subtitle':
          'Usa palabras normales: facturas, ASL, contrato de alquiler, universidad, INPS, documentos. UfficioFacile conecta tu problema con la categoría, los pasos, los documentos y los contactos correctos.',
      'start_problem': 'Empezar por mi problema',
      'browse_procedures': 'Explorar trámites',
      'utilities_bills': 'Facturas y servicios',
      'saved_requests': 'Solicitudes guardadas',
      'what_help': '¿En qué necesitas ayuda?',
      'onboarding_demo_title': 'UfficioFacile',
      'onboarding_demo_subtitle':
          'Gestiona la burocracia italiana sin perderte.',
      'onboarding_card_1_title': 'Encuentra el trámite correcto',
      'onboarding_card_1_body':
          'Elige una categoría y mira qué hacer, dónde ir y qué documentos necesitas.',
      'onboarding_card_2_title': 'Usa contactos verificados',
      'onboarding_card_2_body':
          'Obtén enlaces oficiales, oficinas, direcciones PEC, correos y formularios cuando estén disponibles.',
      'onboarding_card_3_title': 'Desbloquea ayuda Premium',
      'onboarding_card_3_body':
          'Ahorra tiempo con guías más profundas, solicitudes de nuevos problemas y soporte privado.',
      'profile': 'Perfil',
      'profile_full_name': 'Nombre completo',
      'profile_codice_fiscale': 'Código fiscal',
      'profile_city': 'Ciudad',
      'profile_language': 'Idioma',
      'profile_backend_mode': 'Modo backend',
      'profile_backend_supabase': 'Sincronización Supabase activa',
      'profile_backend_local': 'Modo solo local',
      'profile_save': 'Guardar perfil',
      'profile_saving': 'Guardando perfil...',
      'profile_saved': 'Perfil guardado',
      'profile_save_failed': 'No hemos podido guardar el perfil ahora mismo.',
      'profile_sync_settings': 'Ajustes de sincronización',
      'scan_situation': 'Analizar mi situación',
      'document_vault': 'Archivo de documentos',
      'contacts_directory': 'Directorio de contactos',
      'official_links': 'Enlaces oficiales',
      'cost_dashboard': 'Panel de costes',
      'premium_locked_title': 'Guía Premium',
      'unlock_this_guide_only': 'Desbloquear solo esta guía',
      'single_unlock_available': 'Desbloqueo único disponible',
      'payment_not_active_yet': 'El pago todavía no está activo.',
      'upgrade_to_premium': 'Pasar a Premium',
      'my_italy_life': 'Mi vida en Italia',
      'checklist_progress': 'Progreso de la lista',
      'deadlines_short': 'Plazos',
      'city_pack_title': 'Paquete de ciudad',
      'city_catalog_label': 'Ciudad del catálogo',
      'city_catalog_chip_prefix': 'Ciudad',
      'city_catalog_selector': 'Ciudad de las guías',
      'city_catalog_selector_help':
          'Elige la ciudad cuyas guías locales verificadas quieres consultar.',
      'city_catalog_status_available': 'disponible',
      'city_catalog_status_coming_soon': 'próximamente',
      'city_catalog_unavailable_title':
          'Las guías de esta ciudad todavía no están disponibles',
      'city_catalog_unavailable_body':
          'Todavía no tenemos guías locales verificadas para {city}.',
      'city_catalog_request_cta': 'Solicitar esta ciudad',
      'city_catalog_request_saved': 'Solicitud de ciudad guardada.',
      'city_catalog_change_city': 'Cambiar ciudad',
      'city_catalog_select_warning':
          '{city} todavía no está disponible por completo. Puedes guardarla ahora y las guías locales aparecerán cuando añadamos datos verificados.',
      'city_catalog_search_unavailable':
          'Todavía no hay resultados verificados para {city}.',
      'city_catalog_premium_unavailable':
          'Premium está activo, pero las guías de {city} todavía no están disponibles.',
      'estimated_expenses': 'Gastos estimados',
      'cost_dashboard_summary':
          'Sigue tasas, reembolsos, cuotas e importes en disputa.',
      'category_health_asl': 'Salud / ASL',
      'category_housing_rent': 'Vivienda / Alquiler',
      'category_utilities': 'Facturas y servicios',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'Internet y teléfono',
      'category_public_office': 'Comune / Registro',
      'category_work_inps': 'Trabajo / INPS',
      'category_university': 'Universidad / Estudiante',
      'category_general': 'General',
      'category_general_help': 'Ayuda administrativa general',
      'trust_title': 'Confianza',
      'problem_input_placeholder':
          'Describe el problema con tus propias palabras.',
      'search_placeholder_generic':
          'Buscar por título, etiqueta o descripción...',
      'problem_example_1': 'Quiero quitar el Canone RAI de mi factura',
      'problem_example_2': 'Mi factura de gas es demasiado alta',
      'problem_example_3': 'Necesito cambiar de médico de cabecera',
      'problem_example_4': 'Quiero cancelar internet',
      'problem_example_5': 'Mi casero no arregla la calefacción',
      'problem_example_6': 'Necesito la NASpI',
      'all_label': 'Todo',
      'no_procedures_yet_title': 'Todavía no hay trámites',
      'no_procedures_yet_body':
          'Esta categoría todavía no tiene trámites activos.',
      'onboarding_scope_title': '¿Con qué puede ayudarte UfficioFacile?',
      'onboarding_scope_body':
          'Facturas, Canone RAI, salud, alquiler, telecomunicaciones, trabajo, universidad, ayudas, préstamos, reembolsos y gestiones con oficinas públicas.',
      'privacy_title': 'Privacidad y aviso',
      'privacy_body':
          'UfficioFacile te ayuda a organizar los pasos y escribir con claridad. Verifica siempre las reglas oficiales, las oficinas, los plazos y los requisitos antes de enviar algo.',
      'optional_profile_setup': 'Perfil opcional',
      'full_name': 'Nombre completo',
      'codice_fiscale': 'Codice fiscale',
      'city_label': 'Ciudad',
      'auth_email': 'Correo electrónico',
      'plan_title': 'Tu plan',
      'plan_intro':
          'Elige el nivel de ayuda que mejor se adapte a tu situación.',
      'plan_screenshot_limit_note':
          'Las cuentas gratuitas no pueden hacer capturas de pantalla. Premium elimina ese bloqueo en este dispositivo.',
      'current_plan_label': 'Plan actual',
      'free_plan_label': 'Gratis',
      'plus_plan_label': 'Plus',
      'premium_plan_label': 'Premium',
      'catalog_load_error':
          'No se pudo cargar el catálogo. Actualiza la aplicación.',
      'retry': 'Reintentar',
      'signed_out': 'Sesión cerrada',
      'not_found': 'No pudimos encontrar esa página.',
      'back_to_dashboard': 'Volver al panel',
      'one_shot_consultancy_label': 'Consultoría puntual',
      'admin_grant_label': 'Concesión admin',
      'free_plan_desc':
          'Categorías públicas, búsqueda inteligente y guías básicas con límites.',
      'plus_plan_desc':
          'Más packs, más solicitudes guardadas, paneles ampliados y solicitudes prioritarias.',
      'premium_plan_desc':
          'Todas las guías Premium, todas las categorías para ahorrar dinero, archivos completos, escáner avanzado, recordatorios y ayuda privada.',
      'paywall_open_plan': 'Ver planes',
      'paywall_maybe_later': 'Quizá más tarde',
      'payment_setup_message':
          'Las opciones de compra aparecen cuando la facturación está configurada para tu espacio.',
      'sync_same_device_notice':
          'Inicia sesión para sincronizar tus datos de UfficioFacile con este mismo dispositivo verificado.',
      'already_unlocked': 'Ya desbloqueado',
      'of_label': 'de',
      'packs_used_this_month': 'packs usados este mes',
      'onboarding_title': 'Burocracia italiana, paso a paso.',
      'onboarding_subtitle':
          'Organiza trámites, recordatorios, documentos y mensajes formales para facturas, alquiler, salud, universidad y oficinas públicas.',
      'skip': 'Omitir',
      'next': 'Siguiente',
      'done': 'Listo',
      'help': 'Ayuda',
      'admin': 'Admin',
      'generate_pack': 'Generar pack',
      'save_request': 'Guardar solicitud',
      'copied': 'Copiado',
      'request_saved': 'Solicitud guardada',
      'short_message': 'Mensaje corto',
      'email': 'Correo electrónico',
      'pec': 'PEC / Formal',
      'follow_up': 'Seguimiento',
      'strong_follow_up': 'Seguimiento firme',
      'attachments': 'Adjuntos',
      'next_steps': 'Siguientes pasos',
      'warnings': 'Avisos',
      'disclaimer_short':
          'Solo apoyo práctico de redacción y organización. Verifica siempre las instrucciones finales en la web oficial o con la oficina competente.',
      'upcoming_reminders': 'Próximos recordatorios',
      'requests_follow_up': 'Necesitan seguimiento',
      'drafts': 'Borradores',
      'recent_requests': 'Solicitudes recientes',
      'problem_examples': 'Ejemplos',
      'recommendations': 'Flujos recomendados',
      'no_results':
          'Todavía no hay un resultado cercano. Aun así puedes usar la solicitud formal general.',
      'compare_offers': 'Comparar ofertas',
      'understand_bill': 'Entender mi factura',
      'canone_rai': 'Canone RAI',
      'telecom': 'Internet y teléfono',
      'admin_panel': 'Panel admin',
      'demo_data': 'Datos de ejemplo',
      'city_packs': 'Packs de ciudad',
      'student_mode': 'Modo estudiante',
      'tenant_mode': 'Modo inquilino',
      'life_checklist': 'Mi checklist en Italia',
      'proof_folder': 'Carpeta de pruebas',
      'calendar': 'Calendario',
      'plan': 'Plan',
      'free_plan': 'Gratis',
      'pro_plan': 'Premium',
      'consultant_plan': 'Consultoría',
      'beta_access_active': 'Acceso de pago activo',
      'upgrade_to_pro': 'Pasar a Premium',
      'premium_feature': 'Función Premium',
      'auth_account': 'Cuenta',
      'auth_login': 'Iniciar sesión',
      'auth_create_account': 'Crear cuenta',
      'auth_password': 'Contraseña',
      'auth_continue_public': 'Seguir viendo las guías públicas',
      'auth_login_subtitle':
          'Usa tu correo y tu contraseña para abrir tu espacio privado.',
      'auth_signup_subtitle':
          'Crea una cuenta para guardar y sincronizar solicitudes, recordatorios y detalles de documentos.',
      'auth_login_or_signup': 'Iniciar sesión o crear cuenta',
      'auth_required_title': 'Cuenta requerida',
      'auth_required_message':
          'Crea una cuenta para guardar y sincronizar documentos, solicitudes y recordatorios.',
      'auth_required_feature': 'Necesitas una cuenta para abrir esta área.',
      'auth_wait': 'Espera...',
      'auth_reset_password': 'Enviar correo para restablecer la contraseña',
      'auth_reset_sent':
          'Correo de restablecimiento enviado. Revisa tu bandeja de entrada.',
      'auth_signup_success':
          'Cuenta creada. Si la confirmación por correo está activada, confirma tu email antes de iniciar sesión.',
      'account_title': 'Mi cuenta',
      'account_email': 'Correo electrónico',
      'account_not_signed_in': 'No has iniciado sesión',
      'account_plan': 'Plan',
      'account_log_out': 'Cerrar sesión',
      'account_privacy': 'Centro de privacidad',
      'account_delete': 'Eliminar cuenta',
      'access_denied_title': 'Acceso denegado',
      'access_denied_message': 'Tu cuenta no tiene acceso a esta área.',
      'admin_overview': 'Resumen',
      'admin_users': 'Usuarios',
      'admin_premium': 'Premium',
      'admin_catalog': 'Catálogo',
      'admin_problem_requests': 'Solicitudes de problemas',
      'admin_consultancy': 'Consultorías',
      'admin_content_manager': 'Gestor de contenido',
      'admin_security_checklist': 'Checklist de seguridad',
      'admin_supabase_configured': 'Supabase configurado',
      'admin_authenticated': 'Autenticado',
      'admin_rls_enabled':
          'Las escrituras admin protegidas por RLS están activadas por migración',
      'admin_anon_only': 'La app cliente usa solo la clave anon',
      'guided_selector': 'Selector guiado',
      'open': 'Abrir',
      'cta_problem_title': '¿No encuentras tu problema?',
      'cta_problem_body':
          'Cuéntanos qué necesitas. Lo revisaremos y lo añadiremos lo antes posible.',
      'cta_problem_button': 'Solicitar un nuevo problema',
      'cta_problem_thanks':
          'Gracias. Hemos recibido tu solicitud y la revisaremos cuanto antes.',
      'cta_consultancy_title': '¿Necesitas ayuda privada?',
      'cta_consultancy_body':
          'Los miembros Premium pueden solicitar ayuda privada por correo. Los usuarios free pueden pedirla con un pago extra cuando esté disponible.',
      'cta_consultancy_disclaimer':
          'UfficioFacile ofrece guía práctica, no asesoramiento legal, fiscal ni médico. Verifica siempre las instrucciones finales en la web oficial o con la oficina competente.',
      'cta_consultancy_request': 'Solicitar ayuda privada',
      'cta_consultancy_unlock': 'Desbloquear ayuda privada',
      'cta_consultancy_upgrade': 'Pasar a Premium',
      'cta_consultancy_email': 'Enviar mi caso por correo',
      'cta_payment_unavailable':
          'Los pagos Premium todavía no están disponibles. Contacta con soporte.',
      'import_bundled_content': 'Importar el contenido incluido al CMS',
      'startup_loading': 'Iniciando UfficioFacile...',
      'startup_continuing_local': 'Continuando en modo local.',
      'startup_diagnostics': 'Diagnóstico de inicio',
      'startup_continue_local_mode': 'Continuar en modo local',
      'startup_continue_local_only': 'Continuar solo en local',
      'startup_reset_data': 'Restablecer datos de inicio',
      'startup_error_title': 'UfficioFacile no pudo completar el inicio.',
      'startup_unknown_error': 'Error de inicio desconocido.',
      'forgot_password_title': '¿Olvidaste tu contraseña?',
      'forgot_password_intro':
          'Introduce tu correo y enviaremos un enlace de restablecimiento si la cuenta existe.',
      'auth_email_confirmed_title': 'Correo confirmado',
      'auth_email_confirmed_body':
          'Tu cuenta ya está confirmada. Vuelve a iniciar sesión para continuar.',
      'auth_remember_me': 'Recuérdame',
      'auth_remember_me_hint':
          'Guardar tu correo en este dispositivo para acelerar el próximo acceso.',
      'reset_password_title': 'Restablecer contraseña',
      'reset_password_intro': 'Elige una nueva contraseña para tu cuenta.',
      'reset_password_send_link': 'Enviar enlace de restablecimiento',
      'reset_password_sent_generic':
          'Si existe una cuenta para este correo, hemos enviado un enlace de restablecimiento.',
      'confirm_new_password': 'Confirmar nueva contraseña',
      'password_min_length': 'Elige una contraseña de al menos 8 caracteres.',
      'passwords_do_not_match': 'Las contraseñas no coinciden.',
      'password_updated_success': 'Contraseña actualizada correctamente.',
      'update_password': 'Actualizar contraseña',
      'change_password_title': 'Cambiar contraseña',
      'change_password_intro': 'Actualiza la contraseña de esta cuenta.',
      'auth_confirm_email_message':
          'Revisa tu correo para confirmar tu cuenta.',
      'account_change_password': 'Cambiar contraseña',
      'paywall_premium_body':
          'Esta guía forma parte de UfficioFacile Premium. Puedes seguir viendo las guías gratuitas o elegir un plan para desbloquear checklists más profundas, plantillas y soporte privado.',
      'paywall_section_locked_body':
          'Esta sección forma parte de UfficioFacile Premium.',
      'paywall_usage_label': 'Uso',
      'request_consultancy': 'Solicitar consultoría',
      'choose_plan': 'Elegir plan',
    },
    'ar': {
      'app_title': 'UfficioFacile',
      'hero_title': 'اشرح لنا المشكلة. وسنجد لك الإجراء الإيطالي المناسب.',
      'hero_subtitle':
          'استخدم كلمات عادية: فواتير، ASL، عقد إيجار، جامعة، INPS، مستندات. يربط UfficioFacile مشكلتك بالفئة والخطوات والمستندات وجهات الاتصال المناسبة.',
      'start_problem': 'ابدأ من مشكلتي',
      'browse_procedures': 'تصفح الإجراءات',
      'utilities_bills': 'الفواتير والخدمات',
      'saved_requests': 'الطلبات المحفوظة',
      'what_help': 'ما الذي تحتاج إلى مساعدة فيه؟',
      'onboarding_demo_title': 'UfficioFacile',
      'onboarding_demo_subtitle':
          'تعامل مع البيروقراطية الإيطالية بدون أن تضيع.',
      'onboarding_card_1_title': 'اعثر على الإجراء الصحيح',
      'onboarding_card_1_body':
          'اختر فئة لترى ماذا تفعل وأين تذهب وما المستندات المطلوبة.',
      'onboarding_card_2_title': 'استخدم جهات اتصال موثقة',
      'onboarding_card_2_body':
          'احصل على الروابط الرسمية والمكاتب وعناوين PEC ورسائل البريد والنماذج عند توفرها.',
      'onboarding_card_3_title': 'افتح المساعدة Premium',
      'onboarding_card_3_body':
          'وفّر الوقت مع أدلة أعمق وطلبات لمشكلات جديدة ودعم خاص.',
      'profile': 'الملف الشخصي',
      'profile_full_name': 'الاسم الكامل',
      'profile_codice_fiscale': 'الرمز الضريبي',
      'profile_city': 'المدينة',
      'profile_language': 'اللغة',
      'profile_backend_mode': 'وضع الخلفية',
      'profile_backend_supabase': 'مزامنة Supabase مفعلة',
      'profile_backend_local': 'وضع محلي فقط',
      'profile_save': 'حفظ الملف الشخصي',
      'profile_saving': 'جارٍ حفظ الملف الشخصي...',
      'profile_saved': 'تم حفظ الملف الشخصي',
      'profile_save_failed': 'تعذر حفظ الملف الشخصي الآن.',
      'profile_sync_settings': 'إعدادات المزامنة',
      'scan_situation': 'افحص وضعي',
      'document_vault': 'أرشيف المستندات',
      'contacts_directory': 'دليل جهات الاتصال',
      'official_links': 'الروابط الرسمية',
      'cost_dashboard': 'لوحة التكاليف',
      'premium_locked_title': 'دليل Premium',
      'unlock_this_guide_only': 'افتح هذا الدليل فقط',
      'single_unlock_available': 'فتح منفرد متاح',
      'payment_not_active_yet': 'الدفع غير مفعل بعد.',
      'upgrade_to_premium': 'الترقية إلى Premium',
      'my_italy_life': 'حياتي في إيطاليا',
      'checklist_progress': 'تقدم القائمة',
      'deadlines_short': 'المواعيد',
      'city_pack_title': 'حزمة المدينة',
      'city_catalog_label': 'مدينة الدليل',
      'city_catalog_chip_prefix': 'المدينة',
      'city_catalog_selector': 'مدينة الأدلة',
      'city_catalog_selector_help':
          'اختر المدينة التي تريد تصفح أدلتها المحلية الموثقة.',
      'city_catalog_status_available': 'متاح',
      'city_catalog_status_coming_soon': 'قريبًا',
      'city_catalog_unavailable_title': 'أدلة هذه المدينة غير متاحة بعد',
      'city_catalog_unavailable_body':
          'لا نملك أدلة محلية موثقة لمدينة {city} حتى الآن.',
      'city_catalog_request_cta': 'اطلب هذه المدينة',
      'city_catalog_request_saved': 'تم حفظ طلب المدينة.',
      'city_catalog_change_city': 'تغيير المدينة',
      'city_catalog_select_warning':
          '{city} غير متاحة بالكامل بعد. يمكنك حفظها الآن وستظهر الأدلة المحلية عندما نضيف بيانات موثقة.',
      'city_catalog_search_unavailable':
          'لا توجد نتائج موثقة لمدينة {city} بعد.',
      'city_catalog_premium_unavailable':
          'الاشتراك المميز نشط، لكن أدلة {city} غير متاحة بعد.',
      'estimated_expenses': 'المصاريف المقدرة',
      'cost_dashboard_summary':
          'تابع الرسوم والاستردادات والأقساط والمبالغ المتنازع عليها.',
      'category_health_asl': 'الصحة / ASL',
      'category_housing_rent': 'السكن / الإيجار',
      'category_utilities': 'الفواتير والخدمات',
      'category_canone_rai': 'Canone RAI',
      'category_telecom': 'الإنترنت والهاتف',
      'category_public_office': 'البلدية / السجل',
      'category_work_inps': 'العمل / INPS',
      'category_university': 'الجامعة / الطالب',
      'category_general': 'عام',
      'category_general_help': 'مساعدة إدارية عامة',
      'trust_title': 'الثقة',
      'problem_input_placeholder': 'اشرح المشكلة بكلماتك.',
      'search_placeholder_generic': 'ابحث حسب العنوان أو الوسم أو الوصف...',
      'problem_example_1': 'أريد إزالة Canone RAI من الفاتورة',
      'problem_example_2': 'فاتورة الغاز مرتفعة جداً',
      'problem_example_3': 'أحتاج إلى تغيير طبيب الأسرة',
      'problem_example_4': 'أريد إلغاء الإنترنت',
      'problem_example_5': 'المالك لا يصلح التدفئة',
      'problem_example_6': 'أحتاج إلى NASpI',
      'all_label': 'الكل',
      'no_procedures_yet_title': 'لا توجد إجراءات بعد',
      'no_procedures_yet_body': 'لا تحتوي هذه الفئة على إجراءات نشطة حتى الآن.',
      'onboarding_scope_title': 'في ماذا يمكن أن يساعدك UfficioFacile؟',
      'onboarding_scope_body':
          'الفواتير، Canone RAI، الصحة، الإيجار، الاتصالات، العمل، الجامعة، المساعدات، القروض، الاستردادات، والمعاملات مع الجهات العامة.',
      'privacy_title': 'الخصوصية والتنبيه',
      'privacy_body':
          'يساعدك UfficioFacile على ترتيب الخطوات والكتابة بوضوح. تحقق دائماً من القواعد الرسمية والجهات والمواعيد والشروط قبل إرسال أي شيء.',
      'optional_profile_setup': 'إعداد ملف شخصي اختياري',
      'full_name': 'الاسم الكامل',
      'codice_fiscale': 'الرمز الضريبي',
      'city_label': 'المدينة',
      'auth_email': 'البريد الإلكتروني',
      'plan_title': 'خطتك',
      'plan_intro': 'اختر مستوى المساعدة المناسب لوضعك.',
      'plan_screenshot_limit_note':
          'الحسابات المجانية لا يمكنها التقاط لقطات شاشة. يزيل Premium هذا الحظر على هذا الجهاز.',
      'current_plan_label': 'الخطة الحالية',
      'free_plan_label': 'مجاني',
      'plus_plan_label': 'Plus',
      'premium_plan_label': 'Premium',
      'catalog_load_error': 'تعذر تحميل الكتالوج. يرجى تحديث التطبيق.',
      'retry': 'إعادة المحاولة',
      'signed_out': 'تم تسجيل الخروج',
      'not_found': 'تعذر العثور على هذه الصفحة.',
      'back_to_dashboard': 'العودة إلى لوحة التحكم',
      'one_shot_consultancy_label': 'استشارة لمرة واحدة',
      'admin_grant_label': 'منحة إدارية',
      'free_plan_desc': 'فئات عامة وبحث ذكي وإرشاد أساسي مع حدود استخدام.',
      'plus_plan_desc':
          'حزم أكثر، طلبات محفوظة أكثر، لوحات أكبر، وطلبات ذات أولوية.',
      'premium_plan_desc':
          'جميع الأدلة المميزة، كل الفئات التي تساعد على التوفير، أرشيفات كاملة، فحص متقدم، تذكيرات، ومساعدة خاصة.',
      'paywall_open_plan': 'عرض الخطط',
      'paywall_maybe_later': 'ربما لاحقاً',
      'payment_setup_message':
          'تظهر خيارات الشراء عندما يتم تفعيل الفوترة لمساحة العمل الخاصة بك.',
      'sync_same_device_notice':
          'سجّل الدخول لمزامنة بيانات UfficioFacile مع هذا الجهاز الموثق نفسه.',
      'already_unlocked': 'مفتوح بالفعل',
      'of_label': 'من',
      'packs_used_this_month': 'حزم مستخدمة هذا الشهر',
      'onboarding_title': 'الإدارة الإيطالية خطوة بخطوة.',
      'onboarding_subtitle':
          'نظّم الإجراءات والتذكيرات والمستندات والرسائل الرسمية للفواتير والإيجار والصحة والجامعة والجهات العامة.',
      'skip': 'تخطي',
      'next': 'التالي',
      'done': 'تم',
      'help': 'مساعدة',
      'admin': 'المشرف',
      'generate_pack': 'إنشاء حزمة',
      'save_request': 'حفظ الطلب',
      'copied': 'تم النسخ',
      'request_saved': 'تم حفظ الطلب',
      'short_message': 'رسالة قصيرة',
      'email': 'البريد الإلكتروني',
      'pec': 'PEC / رسمي',
      'follow_up': 'متابعة',
      'strong_follow_up': 'متابعة أقوى',
      'attachments': 'مرفقات',
      'next_steps': 'الخطوات التالية',
      'warnings': 'تنبيهات',
      'disclaimer_short':
          'دعم عملي للتنظيم والصياغة فقط. تحقّق دائماً من التعليمات النهائية على الموقع الرسمي أو مع الجهة المختصة.',
      'upcoming_reminders': 'تذكيرات قادمة',
      'requests_follow_up': 'تحتاج متابعة',
      'drafts': 'مسودات',
      'recent_requests': 'طلبات حديثة',
      'problem_examples': 'أمثلة',
      'recommendations': 'مسارات موصى بها',
      'no_results':
          'لا توجد نتيجة قريبة بعد. ما زال بإمكانك استخدام الطلب الرسمي العام.',
      'compare_offers': 'مقارنة العروض',
      'understand_bill': 'فهم فاتورتي',
      'canone_rai': 'Canone RAI',
      'telecom': 'الإنترنت والهاتف',
      'admin_panel': 'لوحة المشرف',
      'demo_data': 'بيانات تجريبية',
      'city_packs': 'حزم المدن',
      'student_mode': 'وضع الطالب',
      'tenant_mode': 'وضع المستأجر',
      'life_checklist': 'قائمتي في إيطاليا',
      'proof_folder': 'مجلد الإثباتات',
      'calendar': 'التقويم',
      'plan': 'الخطة',
      'free_plan': 'مجاني',
      'pro_plan': 'Premium',
      'consultant_plan': 'استشارة',
      'beta_access_active': 'وصول مدفوع نشط',
      'upgrade_to_pro': 'الترقية إلى Premium',
      'premium_feature': 'ميزة Premium',
      'auth_account': 'الحساب',
      'auth_login': 'تسجيل الدخول',
      'auth_create_account': 'إنشاء حساب',
      'auth_password': 'كلمة المرور',
      'auth_continue_public': 'متابعة تصفح الأدلة العامة',
      'auth_login_subtitle':
          'استخدم بريدك الإلكتروني وكلمة المرور لفتح مساحتك الخاصة.',
      'auth_signup_subtitle':
          'أنشئ حساباً لحفظ الطلبات والتذكيرات وتفاصيل المستندات ومزامنتها.',
      'auth_login_or_signup': 'تسجيل الدخول أو إنشاء حساب',
      'auth_required_title': 'الحساب مطلوب',
      'auth_required_message':
          'أنشئ حساباً لحفظ المستندات والطلبات والتذكيرات ومزامنتها.',
      'auth_required_feature': 'تحتاج إلى حساب لفتح هذه المنطقة.',
      'auth_wait': 'يرجى الانتظار...',
      'auth_reset_password': 'إرسال رسالة إعادة تعيين كلمة المرور',
      'auth_reset_sent':
          'تم إرسال رسالة إعادة تعيين كلمة المرور. تحقّق من بريدك الوارد.',
      'auth_signup_success':
          'تم إنشاء الحساب. إذا كان تأكيد البريد الإلكتروني مفعلاً، أكّد بريدك قبل تسجيل الدخول.',
      'account_title': 'حسابي',
      'account_email': 'البريد الإلكتروني',
      'account_not_signed_in': 'لست مسجلاً للدخول',
      'account_plan': 'الخطة',
      'account_log_out': 'تسجيل الخروج',
      'account_privacy': 'مركز الخصوصية',
      'account_delete': 'حذف الحساب',
      'access_denied_title': 'تم رفض الوصول',
      'access_denied_message': 'حسابك لا يملك صلاحية الوصول إلى هذه المنطقة.',
      'admin_overview': 'نظرة عامة',
      'admin_users': 'المستخدمون',
      'admin_premium': 'Premium',
      'admin_catalog': 'الكتالوج',
      'admin_problem_requests': 'طلبات المشاكل',
      'admin_consultancy': 'طلبات الاستشارة',
      'admin_content_manager': 'إدارة المحتوى',
      'admin_security_checklist': 'قائمة فحص الأمان',
      'admin_supabase_configured': 'تم إعداد Supabase',
      'admin_authenticated': 'تم تسجيل الدخول',
      'admin_rls_enabled':
          'عمليات الكتابة الإدارية المحمية بـ RLS مفعلة عبر الهجرة',
      'admin_anon_only': 'تستخدم تطبيقات العميل مفتاح anon فقط',
      'guided_selector': 'اختيار موجه',
      'open': 'فتح',
      'cta_problem_title': 'لا تجد مشكلتك؟',
      'cta_problem_body': 'أخبرنا بما تحتاجه. سنراجعه ونضيفه بأسرع ما يمكن.',
      'cta_problem_button': 'طلب مشكلة جديدة',
      'cta_problem_thanks': 'شكراً. تلقينا طلبك وسنراجعه في أقرب وقت ممكن.',
      'cta_consultancy_title': 'هل تحتاج إلى مساعدة خاصة؟',
      'cta_consultancy_body':
          'يمكن لأعضاء Premium طلب مساعدة خاصة عبر البريد الإلكتروني. ويمكن للمستخدمين المجانيين طلبها مقابل دفعة إضافية عند توفرها.',
      'cta_consultancy_disclaimer':
          'يوفر UfficioFacile إرشاداً عملياً فقط، وليس نصيحة قانونية أو ضريبية أو طبية. تحقّق دائماً من التعليمات النهائية على الموقع الرسمي أو مع الجهة المختصة.',
      'cta_consultancy_request': 'طلب مساعدة خاصة',
      'cta_consultancy_unlock': 'فتح المساعدة الخاصة',
      'cta_consultancy_upgrade': 'الترقية إلى Premium',
      'cta_consultancy_email': 'إرسال الحالة بالبريد الإلكتروني',
      'cta_payment_unavailable':
          'مدفوعات Premium غير مفعلة بعد. تواصل مع الدعم.',
      'import_bundled_content': 'استيراد المحتوى المرفق إلى CMS',
      'startup_loading': 'جارٍ تشغيل UfficioFacile...',
      'startup_continuing_local': 'المتابعة في الوضع المحلي.',
      'startup_diagnostics': 'تشخيص بدء التشغيل',
      'startup_continue_local_mode': 'المتابعة في الوضع المحلي',
      'startup_continue_local_only': 'المتابعة محلياً فقط',
      'startup_reset_data': 'إعادة تعيين بيانات البدء',
      'startup_error_title': 'لم يتمكن UfficioFacile من إكمال بدء التشغيل.',
      'startup_unknown_error': 'خطأ غير معروف أثناء البدء.',
      'forgot_password_title': 'هل نسيت كلمة المرور؟',
      'forgot_password_intro':
          'أدخل بريدك الإلكتروني وسنرسل رابط إعادة تعيين إذا كان الحساب موجوداً.',
      'auth_email_confirmed_title': 'تم تأكيد البريد الإلكتروني',
      'auth_email_confirmed_body':
          'تم تأكيد حسابك. سجّل الدخول مرة أخرى للمتابعة.',
      'auth_remember_me': 'تذكّرني',
      'auth_remember_me_hint':
          'الاحتفاظ ببريدك الإلكتروني على هذا الجهاز لتسريع تسجيل الدخول لاحقاً.',
      'reset_password_title': 'إعادة تعيين كلمة المرور',
      'reset_password_intro': 'اختر كلمة مرور جديدة لحسابك.',
      'reset_password_send_link': 'إرسال رابط إعادة التعيين',
      'reset_password_sent_generic':
          'إذا كان هناك حساب لهذا البريد، فقد أرسلنا رابط إعادة التعيين.',
      'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
      'password_min_length': 'اختر كلمة مرور لا تقل عن 8 أحرف.',
      'passwords_do_not_match': 'كلمتا المرور غير متطابقتين.',
      'password_updated_success': 'تم تحديث كلمة المرور بنجاح.',
      'update_password': 'تحديث كلمة المرور',
      'change_password_title': 'تغيير كلمة المرور',
      'change_password_intro': 'حدّث كلمة المرور لهذا الحساب.',
      'auth_confirm_email_message': 'تحقق من بريدك الإلكتروني لتأكيد حسابك.',
      'account_change_password': 'تغيير كلمة المرور',
      'paywall_premium_body':
          'هذا الدليل جزء من UfficioFacile Premium. ما زال بإمكانك تصفح الأدلة المجانية أو اختيار خطة لفتح قوائم تحقق أعمق وقوالب ودعم خاص.',
      'paywall_section_locked_body': 'هذا القسم جزء من UfficioFacile Premium.',
      'paywall_usage_label': 'الاستخدام',
      'request_consultancy': 'طلب استشارة',
      'choose_plan': 'اختيار الخطة',
    },
  };
}

class AppLocalizationsScope extends InheritedWidget {
  const AppLocalizationsScope({
    super.key,
    required this.localizations,
    required super.child,
  });

  final AppLocalizations localizations;

  static AppLocalizations of(BuildContext context) {
    final scope = context
        .dependOnInheritedWidgetOfExactType<AppLocalizationsScope>();
    return scope?.localizations ?? AppLocalizations('en');
  }

  @override
  bool updateShouldNotify(AppLocalizationsScope oldWidget) {
    return oldWidget.localizations.languageCode != localizations.languageCode;
  }
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizationsScope.of(this);
}
